// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/application/contracts/application_builder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	contracts "frisboo-bank/openapi-generator-service/pkg/application/contracts"
	contracts0 "frisboo-bank/openapi-generator-service/pkg/config/contracts"
	contracts1 "frisboo-bank/openapi-generator-service/pkg/container/contracts"
	environment "frisboo-bank/openapi-generator-service/pkg/environment/models/enums/environment"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApplicationBuilder is a mock of ApplicationBuilder interface.
type MockApplicationBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationBuilderMockRecorder
}

// MockApplicationBuilderMockRecorder is the mock recorder for MockApplicationBuilder.
type MockApplicationBuilderMockRecorder struct {
	mock *MockApplicationBuilder
}

// NewMockApplicationBuilder creates a new mock instance.
func NewMockApplicationBuilder(ctrl *gomock.Controller) *MockApplicationBuilder {
	mock := &MockApplicationBuilder{ctrl: ctrl}
	mock.recorder = &MockApplicationBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationBuilder) EXPECT() *MockApplicationBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockApplicationBuilder) Build() (contracts.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(contracts.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockApplicationBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockApplicationBuilder)(nil).Build))
}

// ConfigLoader mocks base method.
func (m *MockApplicationBuilder) ConfigLoader() contracts0.ConfigLoader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigLoader")
	ret0, _ := ret[0].(contracts0.ConfigLoader)
	return ret0
}

// ConfigLoader indicates an expected call of ConfigLoader.
func (mr *MockApplicationBuilderMockRecorder) ConfigLoader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigLoader", reflect.TypeOf((*MockApplicationBuilder)(nil).ConfigLoader))
}

// Environment mocks base method.
func (m *MockApplicationBuilder) Environment() environment.Environment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Environment")
	ret0, _ := ret[0].(environment.Environment)
	return ret0
}

// Environment indicates an expected call of Environment.
func (mr *MockApplicationBuilderMockRecorder) Environment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Environment", reflect.TypeOf((*MockApplicationBuilder)(nil).Environment))
}

// ProvideDecorator mocks base method.
func (m *MockApplicationBuilder) ProvideDecorator(decorators ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range decorators {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ProvideDecorator", varargs...)
}

// ProvideDecorator indicates an expected call of ProvideDecorator.
func (mr *MockApplicationBuilderMockRecorder) ProvideDecorator(decorators ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideDecorator", reflect.TypeOf((*MockApplicationBuilder)(nil).ProvideDecorator), decorators...)
}

// ProvideModule mocks base method.
func (m *MockApplicationBuilder) ProvideModule(module ...contracts1.Module) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range module {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ProvideModule", varargs...)
}

// ProvideModule indicates an expected call of ProvideModule.
func (mr *MockApplicationBuilderMockRecorder) ProvideModule(module ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideModule", reflect.TypeOf((*MockApplicationBuilder)(nil).ProvideModule), module...)
}

// ProvideProvider mocks base method.
func (m *MockApplicationBuilder) ProvideProvider(providers ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range providers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ProvideProvider", varargs...)
}

// ProvideProvider indicates an expected call of ProvideProvider.
func (mr *MockApplicationBuilderMockRecorder) ProvideProvider(providers ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideProvider", reflect.TypeOf((*MockApplicationBuilder)(nil).ProvideProvider), providers...)
}
