// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/mediator/contracts/mediator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	contracts "frisboo-bank/openapi-generator-service/pkg/application_error/contracts"
	contracts0 "frisboo-bank/openapi-generator-service/pkg/mediator/contracts"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestHandler is a mock of RequestHandler interface.
type MockRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRequestHandlerMockRecorder
}

// MockRequestHandlerMockRecorder is the mock recorder for MockRequestHandler.
type MockRequestHandlerMockRecorder struct {
	mock *MockRequestHandler
}

// NewMockRequestHandler creates a new mock instance.
func NewMockRequestHandler(ctrl *gomock.Controller) *MockRequestHandler {
	mock := &MockRequestHandler{ctrl: ctrl}
	mock.recorder = &MockRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestHandler) EXPECT() *MockRequestHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockRequestHandler) Handle(ctx context.Context, request contracts0.TRequest) (contracts0.TResponse, contracts.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, request)
	ret0, _ := ret[0].(contracts0.TResponse)
	ret1, _ := ret[1].(contracts.AppError)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockRequestHandlerMockRecorder) Handle(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockRequestHandler)(nil).Handle), ctx, request)
}

// MockNotificationHandler is a mock of NotificationHandler interface.
type MockNotificationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationHandlerMockRecorder
}

// MockNotificationHandlerMockRecorder is the mock recorder for MockNotificationHandler.
type MockNotificationHandlerMockRecorder struct {
	mock *MockNotificationHandler
}

// NewMockNotificationHandler creates a new mock instance.
func NewMockNotificationHandler(ctrl *gomock.Controller) *MockNotificationHandler {
	mock := &MockNotificationHandler{ctrl: ctrl}
	mock.recorder = &MockNotificationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationHandler) EXPECT() *MockNotificationHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockNotificationHandler) Handle(ctx context.Context, notification contracts0.TNotification) contracts.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, notification)
	ret0, _ := ret[0].(contracts.AppError)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockNotificationHandlerMockRecorder) Handle(ctx, notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockNotificationHandler)(nil).Handle), ctx, notification)
}

// MockMediator is a mock of Mediator interface.
type MockMediator struct {
	ctrl     *gomock.Controller
	recorder *MockMediatorMockRecorder
}

// MockMediatorMockRecorder is the mock recorder for MockMediator.
type MockMediatorMockRecorder struct {
	mock *MockMediator
}

// NewMockMediator creates a new mock instance.
func NewMockMediator(ctrl *gomock.Controller) *MockMediator {
	mock := &MockMediator{ctrl: ctrl}
	mock.recorder = &MockMediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediator) EXPECT() *MockMediatorMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMediator) Publish(ctx context.Context, notification contracts0.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMediatorMockRecorder) Publish(ctx, notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMediator)(nil).Publish), ctx, notification)
}

// RegisterNotification mocks base method.
func (m *MockMediator) RegisterNotification(notificationType contracts0.TNotification, handler any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNotification", notificationType, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterNotification indicates an expected call of RegisterNotification.
func (mr *MockMediatorMockRecorder) RegisterNotification(notificationType, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNotification", reflect.TypeOf((*MockMediator)(nil).RegisterNotification), notificationType, handler)
}

// RegisterRequest mocks base method.
func (m *MockMediator) RegisterRequest(requestType contracts0.TRequest, handler any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRequest", requestType, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterRequest indicates an expected call of RegisterRequest.
func (mr *MockMediatorMockRecorder) RegisterRequest(requestType, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRequest", reflect.TypeOf((*MockMediator)(nil).RegisterRequest), requestType, handler)
}

// Send mocks base method.
func (m *MockMediator) Send(ctx context.Context, request contracts0.Request) (contracts0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, request)
	ret0, _ := ret[0].(contracts0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMediatorMockRecorder) Send(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMediator)(nil).Send), ctx, request)
}
