// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:46.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/cache_type/cache_type.go

package cachetype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// CacheType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type CacheType struct {
	cacheType
}

// cacheTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the CacheType type.
type cacheTypesContainer struct {
	UNKNOWN CacheType
	REDIS   CacheType
	MEMORY  CacheType
}

// CacheTypes is a main entry point using the CacheType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var CacheTypes = cacheTypesContainer{
	UNKNOWN: CacheType{
		cacheType: unknown,
	},
	REDIS: CacheType{
		cacheType: redis,
	},
	MEMORY: CacheType{
		cacheType: memory,
	},
}

// invalidCacheType is an invalid sentinel value for CacheType
var invalidCacheType = CacheType{
	cacheType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c cacheTypesContainer) allSlice() []CacheType {
	return []CacheType{
		CacheTypes.REDIS,
		CacheTypes.MEMORY,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c cacheTypesContainer) All() iter.Seq[CacheType] {
	return func(yield func(CacheType) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseCacheType = errors.New("invalid input provided to parse to CacheType")

// ParseCacheType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseCacheType(input any) (CacheType, error) {
	switch v := input.(type) {
	case CacheType:
		return v, nil
	case string:
		if result := stringToCacheType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToCacheType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToCacheType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToCacheType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidCacheType, fmt.Errorf("invalid type %T", input)
	}
	return invalidCacheType, fmt.Errorf("%w: invalid value %v", ErrParseCacheType, input)
}

// cacheTypesNameMap is a map of enum values to their CacheType representation
// It is used to convert string representations of enum values into their CacheType representation.
var cacheTypesNameMap = map[string]CacheType{
	"unknown": CacheTypes.UNKNOWN,
	"redis":   CacheTypes.REDIS,
	"memory":  CacheTypes.MEMORY,
}

// stringToCacheType converts a string representation of an enum value into its CacheType representation
// It returns a pointer to the CacheType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToCacheType(s string) *CacheType {
	if t, ok := cacheTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToCacheType converts a numeric value to a CacheType
// It returns a pointer to the CacheType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToCacheType[T number](num T) *CacheType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(CacheTypes.allSlice()) {
		return nil
	}
	result := CacheTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveCacheTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveCacheTypes(f func(CacheType)) {
	for _, p := range CacheTypes.allSlice() {
		f(p)
	}
}

// validCacheTypes is a map of enum values to their validity
var validCacheTypes = map[CacheType]bool{
	CacheTypes.UNKNOWN: false,
	CacheTypes.REDIS:   true,
	CacheTypes.MEMORY:  true,
}

// IsValid checks whether the CacheTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (c CacheType) IsValid() bool {
	return validCacheTypes[c]
}

// MarshalJSON implements the json.Marshaler interface for CacheType.
// It returns the JSON representation of the enum value as a byte slice.
func (c CacheType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for CacheType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (c *CacheType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newc, err := ParseCacheType(b)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for CacheType.
// It returns the string representation of the enum value as a byte slice
func (c CacheType) MarshalText() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CacheType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *CacheType) UnmarshalText(b []byte) error {
	newc, err := ParseCacheType(b)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Scan implements the database/sql.Scanner interface for CacheType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (c *CacheType) Scan(value any) error {
	newc, err := ParseCacheType(value)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Value implements the database/sql/driver.Valuer interface for CacheType.
// It returns the string representation of the enum value.
func (c CacheType) Value() (driver.Value, error) {
	return c.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for CacheType.
// It returns the binary representation of the enum value as a byte slice.
func (c CacheType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for CacheType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *CacheType) UnmarshalBinary(b []byte) error {
	newc, err := ParseCacheType(b)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for CacheType.
// It returns the string representation of the enum value.
func (c CacheType) MarshalYAML() ([]byte, error) {
	return []byte(c.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (c *CacheType) UnmarshalYAML(b []byte) error {
	newc, err := ParseCacheType(b)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// cachetypeNames is a constant string slice containing all enum values cononical absolute names
const cachetypeNames = "unknownredismemory"

// cachetypeNamesMap is a map of enum values to their canonical absolute
// name positions within the cachetypeNames string slice
var cachetypeNamesMap = map[CacheType]string{
	CacheTypes.UNKNOWN: cachetypeNames[0:7],
	CacheTypes.REDIS:   cachetypeNames[7:12],
	CacheTypes.MEMORY:  cachetypeNames[12:18],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (c CacheType) String() string {
	if str, ok := cachetypeNamesMap[c]; ok {
		return str
	}
	return fmt.Sprintf("cachetype(%d)", c.cacheType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[unknown]
	_ = x[redis-1]
	_ = x[memory-2]
}
