// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:46.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/environment/environment.go

package environment

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// Environment is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type Environment struct {
	environment
}

// environmentsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the Environment type.
type environmentsContainer struct {
	UNKNOWN     Environment
	DEVELOPMENT Environment
	PREPROD     Environment
	PRODUCTION  Environment
	TESTING     Environment
}

// Environments is a main entry point using the Environment type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Environments = environmentsContainer{
	UNKNOWN: Environment{
		environment: unknown,
	},
	DEVELOPMENT: Environment{
		environment: development,
	},
	PREPROD: Environment{
		environment: preprod,
	},
	PRODUCTION: Environment{
		environment: production,
	},
	TESTING: Environment{
		environment: testing,
	},
}

// invalidEnvironment is an invalid sentinel value for Environment
var invalidEnvironment = Environment{
	environment: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e environmentsContainer) allSlice() []Environment {
	return []Environment{
		Environments.DEVELOPMENT,
		Environments.PREPROD,
		Environments.PRODUCTION,
		Environments.TESTING,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e environmentsContainer) All() iter.Seq[Environment] {
	return func(yield func(Environment) bool) {
		for _, v := range e.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseEnvironment = errors.New("invalid input provided to parse to Environment")

// ParseEnvironment parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseEnvironment(input any) (Environment, error) {
	switch v := input.(type) {
	case Environment:
		return v, nil
	case string:
		if result := stringToEnvironment(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToEnvironment(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToEnvironment(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToEnvironment(v); result != nil {
			return *result, nil
		}
	default:
		return invalidEnvironment, fmt.Errorf("invalid type %T", input)
	}
	return invalidEnvironment, fmt.Errorf("%w: invalid value %v", ErrParseEnvironment, input)
}

// environmentsNameMap is a map of enum values to their Environment representation
// It is used to convert string representations of enum values into their Environment representation.
var environmentsNameMap = map[string]Environment{
	"unknown":     Environments.UNKNOWN,
	"development": Environments.DEVELOPMENT,
	"preprod":     Environments.PREPROD,
	"production":  Environments.PRODUCTION,
	"testing":     Environments.TESTING,
}

// stringToEnvironment converts a string representation of an enum value into its Environment representation
// It returns a pointer to the Environment representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToEnvironment(s string) *Environment {
	if t, ok := environmentsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToEnvironment converts a numeric value to a Environment
// It returns a pointer to the Environment representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToEnvironment[T number](num T) *Environment {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(Environments.allSlice()) {
		return nil
	}
	result := Environments.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveEnvironments iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveEnvironments(f func(Environment)) {
	for _, p := range Environments.allSlice() {
		f(p)
	}
}

// validEnvironments is a map of enum values to their validity
var validEnvironments = map[Environment]bool{
	Environments.UNKNOWN:     false,
	Environments.DEVELOPMENT: true,
	Environments.PREPROD:     true,
	Environments.PRODUCTION:  true,
	Environments.TESTING:     true,
}

// IsValid checks whether the Environments value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (e Environment) IsValid() bool {
	return validEnvironments[e]
}

// MarshalJSON implements the json.Marshaler interface for Environment.
// It returns the JSON representation of the enum value as a byte slice.
func (e Environment) MarshalJSON() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Environment.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (e *Environment) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newe, err := ParseEnvironment(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Environment.
// It returns the string representation of the enum value as a byte slice
func (e Environment) MarshalText() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Environment.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *Environment) UnmarshalText(b []byte) error {
	newe, err := ParseEnvironment(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Scan implements the database/sql.Scanner interface for Environment.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (e *Environment) Scan(value any) error {
	newe, err := ParseEnvironment(value)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Value implements the database/sql/driver.Valuer interface for Environment.
// It returns the string representation of the enum value.
func (e Environment) Value() (driver.Value, error) {
	return e.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Environment.
// It returns the binary representation of the enum value as a byte slice.
func (e Environment) MarshalBinary() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Environment.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *Environment) UnmarshalBinary(b []byte) error {
	newe, err := ParseEnvironment(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for Environment.
// It returns the string representation of the enum value.
func (e Environment) MarshalYAML() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (e *Environment) UnmarshalYAML(b []byte) error {
	newe, err := ParseEnvironment(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// environmentNames is a constant string slice containing all enum values cononical absolute names
const environmentNames = "unknowndevelopmentpreprodproductiontesting"

// environmentNamesMap is a map of enum values to their canonical absolute
// name positions within the environmentNames string slice
var environmentNamesMap = map[Environment]string{
	Environments.UNKNOWN:     environmentNames[0:7],
	Environments.DEVELOPMENT: environmentNames[7:18],
	Environments.PREPROD:     environmentNames[18:25],
	Environments.PRODUCTION:  environmentNames[25:35],
	Environments.TESTING:     environmentNames[35:42],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (e Environment) String() string {
	if str, ok := environmentNamesMap[e]; ok {
		return str
	}
	return fmt.Sprintf("environment(%d)", e.environment)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[unknown]
	_ = x[development-1]
	_ = x[preprod-2]
	_ = x[production-3]
	_ = x[testing-4]
}
