// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/database/sql_client/contracts/sql_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	contracts "frisboo-bank/openapi-generator-service/pkg/database/sql_client/contracts"
	sqlclienttype "frisboo-bank/openapi-generator-service/pkg/database/sql_client/models/enums/sql_client_type"
	contracts0 "frisboo-bank/openapi-generator-service/pkg/logger/contracts"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQLRow is a mock of SQLRow interface.
type MockSQLRow struct {
	ctrl     *gomock.Controller
	recorder *MockSQLRowMockRecorder
}

// MockSQLRowMockRecorder is the mock recorder for MockSQLRow.
type MockSQLRowMockRecorder struct {
	mock *MockSQLRow
}

// NewMockSQLRow creates a new mock instance.
func NewMockSQLRow(ctrl *gomock.Controller) *MockSQLRow {
	mock := &MockSQLRow{ctrl: ctrl}
	mock.recorder = &MockSQLRowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLRow) EXPECT() *MockSQLRowMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockSQLRow) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockSQLRowMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSQLRow)(nil).Err))
}

// Scan mocks base method.
func (m *MockSQLRow) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockSQLRowMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockSQLRow)(nil).Scan), dest...)
}

// MockSQLRows is a mock of SQLRows interface.
type MockSQLRows struct {
	ctrl     *gomock.Controller
	recorder *MockSQLRowsMockRecorder
}

// MockSQLRowsMockRecorder is the mock recorder for MockSQLRows.
type MockSQLRowsMockRecorder struct {
	mock *MockSQLRows
}

// NewMockSQLRows creates a new mock instance.
func NewMockSQLRows(ctrl *gomock.Controller) *MockSQLRows {
	mock := &MockSQLRows{ctrl: ctrl}
	mock.recorder = &MockSQLRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLRows) EXPECT() *MockSQLRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSQLRows) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLRows)(nil).Close))
}

// ColumnTypes mocks base method.
func (m *MockSQLRows) ColumnTypes() ([]*sql.ColumnType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ColumnTypes")
	ret0, _ := ret[0].([]*sql.ColumnType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ColumnTypes indicates an expected call of ColumnTypes.
func (mr *MockSQLRowsMockRecorder) ColumnTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ColumnTypes", reflect.TypeOf((*MockSQLRows)(nil).ColumnTypes))
}

// Columns mocks base method.
func (m *MockSQLRows) Columns() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Columns")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Columns indicates an expected call of Columns.
func (mr *MockSQLRowsMockRecorder) Columns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Columns", reflect.TypeOf((*MockSQLRows)(nil).Columns))
}

// Err mocks base method.
func (m *MockSQLRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockSQLRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSQLRows)(nil).Err))
}

// Next mocks base method.
func (m *MockSQLRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockSQLRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSQLRows)(nil).Next))
}

// NextResultSet mocks base method.
func (m *MockSQLRows) NextResultSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextResultSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NextResultSet indicates an expected call of NextResultSet.
func (mr *MockSQLRowsMockRecorder) NextResultSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextResultSet", reflect.TypeOf((*MockSQLRows)(nil).NextResultSet))
}

// Scan mocks base method.
func (m *MockSQLRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockSQLRowsMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockSQLRows)(nil).Scan), dest...)
}

// MockSQLClientCore is a mock of SQLClientCore interface.
type MockSQLClientCore struct {
	ctrl     *gomock.Controller
	recorder *MockSQLClientCoreMockRecorder
}

// MockSQLClientCoreMockRecorder is the mock recorder for MockSQLClientCore.
type MockSQLClientCoreMockRecorder struct {
	mock *MockSQLClientCore
}

// NewMockSQLClientCore creates a new mock instance.
func NewMockSQLClientCore(ctrl *gomock.Controller) *MockSQLClientCore {
	mock := &MockSQLClientCore{ctrl: ctrl}
	mock.recorder = &MockSQLClientCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLClientCore) EXPECT() *MockSQLClientCoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSQLClientCore) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLClientCoreMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLClientCore)(nil).Close), ctx)
}

// Logger mocks base method.
func (m *MockSQLClientCore) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSQLClientCoreMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSQLClientCore)(nil).Logger))
}

// Name mocks base method.
func (m *MockSQLClientCore) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSQLClientCoreMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSQLClientCore)(nil).Name))
}

// Ping mocks base method.
func (m *MockSQLClientCore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLClientCoreMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLClientCore)(nil).Ping), ctx)
}

// Type mocks base method.
func (m *MockSQLClientCore) Type() sqlclienttype.SqlClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(sqlclienttype.SqlClientType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSQLClientCoreMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSQLClientCore)(nil).Type))
}

// MockSQLClient is a mock of SQLClient interface.
type MockSQLClient struct {
	ctrl     *gomock.Controller
	recorder *MockSQLClientMockRecorder
}

// MockSQLClientMockRecorder is the mock recorder for MockSQLClient.
type MockSQLClientMockRecorder struct {
	mock *MockSQLClient
}

// NewMockSQLClient creates a new mock instance.
func NewMockSQLClient(ctrl *gomock.Controller) *MockSQLClient {
	mock := &MockSQLClient{ctrl: ctrl}
	mock.recorder = &MockSQLClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLClient) EXPECT() *MockSQLClientMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockSQLClient) BeginTx(ctx context.Context, opts *sql.TxOptions) (contracts.SQLTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(contracts.SQLTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockSQLClientMockRecorder) BeginTx(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockSQLClient)(nil).BeginTx), ctx, opts)
}

// Close mocks base method.
func (m *MockSQLClient) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLClientMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLClient)(nil).Close), ctx)
}

// Exec mocks base method.
func (m *MockSQLClient) Exec(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSQLClientMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSQLClient)(nil).Exec), varargs...)
}

// Logger mocks base method.
func (m *MockSQLClient) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSQLClientMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSQLClient)(nil).Logger))
}

// Name mocks base method.
func (m *MockSQLClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSQLClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSQLClient)(nil).Name))
}

// Ping mocks base method.
func (m *MockSQLClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLClientMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLClient)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockSQLClient) Query(ctx context.Context, query string, args ...any) (contracts.SQLRows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(contracts.SQLRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockSQLClientMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSQLClient)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockSQLClient) QueryRow(ctx context.Context, query string, args ...any) contracts.SQLRow {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(contracts.SQLRow)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockSQLClientMockRecorder) QueryRow(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockSQLClient)(nil).QueryRow), varargs...)
}

// Type mocks base method.
func (m *MockSQLClient) Type() sqlclienttype.SqlClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(sqlclienttype.SqlClientType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSQLClientMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSQLClient)(nil).Type))
}

// MockSQLClientAdapter is a mock of SQLClientAdapter interface.
type MockSQLClientAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSQLClientAdapterMockRecorder
}

// MockSQLClientAdapterMockRecorder is the mock recorder for MockSQLClientAdapter.
type MockSQLClientAdapterMockRecorder struct {
	mock *MockSQLClientAdapter
}

// NewMockSQLClientAdapter creates a new mock instance.
func NewMockSQLClientAdapter(ctrl *gomock.Controller) *MockSQLClientAdapter {
	mock := &MockSQLClientAdapter{ctrl: ctrl}
	mock.recorder = &MockSQLClientAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLClientAdapter) EXPECT() *MockSQLClientAdapterMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockSQLClientAdapter) BeginTx(ctx context.Context, opts *sql.TxOptions) (contracts.SQLTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(contracts.SQLTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockSQLClientAdapterMockRecorder) BeginTx(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockSQLClientAdapter)(nil).BeginTx), ctx, opts)
}

// Close mocks base method.
func (m *MockSQLClientAdapter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLClientAdapterMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLClientAdapter)(nil).Close), ctx)
}

// Exec mocks base method.
func (m *MockSQLClientAdapter) Exec(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSQLClientAdapterMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSQLClientAdapter)(nil).Exec), varargs...)
}

// Logger mocks base method.
func (m *MockSQLClientAdapter) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSQLClientAdapterMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSQLClientAdapter)(nil).Logger))
}

// Name mocks base method.
func (m *MockSQLClientAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSQLClientAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSQLClientAdapter)(nil).Name))
}

// Ping mocks base method.
func (m *MockSQLClientAdapter) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLClientAdapterMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLClientAdapter)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockSQLClientAdapter) Query(ctx context.Context, query string, args ...any) (contracts.SQLRows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(contracts.SQLRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockSQLClientAdapterMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSQLClientAdapter)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockSQLClientAdapter) QueryRow(ctx context.Context, query string, args ...any) contracts.SQLRow {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(contracts.SQLRow)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockSQLClientAdapterMockRecorder) QueryRow(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockSQLClientAdapter)(nil).QueryRow), varargs...)
}

// Type mocks base method.
func (m *MockSQLClientAdapter) Type() sqlclienttype.SqlClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(sqlclienttype.SqlClientType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSQLClientAdapterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSQLClientAdapter)(nil).Type))
}

// MockSQLTransaction is a mock of SQLTransaction interface.
type MockSQLTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockSQLTransactionMockRecorder
}

// MockSQLTransactionMockRecorder is the mock recorder for MockSQLTransaction.
type MockSQLTransactionMockRecorder struct {
	mock *MockSQLTransaction
}

// NewMockSQLTransaction creates a new mock instance.
func NewMockSQLTransaction(ctrl *gomock.Controller) *MockSQLTransaction {
	mock := &MockSQLTransaction{ctrl: ctrl}
	mock.recorder = &MockSQLTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLTransaction) EXPECT() *MockSQLTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockSQLTransaction) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockSQLTransactionMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockSQLTransaction)(nil).Commit), ctx)
}

// Exec mocks base method.
func (m *MockSQLTransaction) Exec(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSQLTransactionMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSQLTransaction)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockSQLTransaction) Query(ctx context.Context, query string, args ...any) (contracts.SQLRows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(contracts.SQLRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockSQLTransactionMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSQLTransaction)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockSQLTransaction) QueryRow(ctx context.Context, query string, args ...any) contracts.SQLRow {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(contracts.SQLRow)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockSQLTransactionMockRecorder) QueryRow(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockSQLTransaction)(nil).QueryRow), varargs...)
}

// Rollback mocks base method.
func (m *MockSQLTransaction) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockSQLTransactionMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockSQLTransaction)(nil).Rollback), ctx)
}

// MockSQLXRows is a mock of SQLXRows interface.
type MockSQLXRows struct {
	ctrl     *gomock.Controller
	recorder *MockSQLXRowsMockRecorder
}

// MockSQLXRowsMockRecorder is the mock recorder for MockSQLXRows.
type MockSQLXRowsMockRecorder struct {
	mock *MockSQLXRows
}

// NewMockSQLXRows creates a new mock instance.
func NewMockSQLXRows(ctrl *gomock.Controller) *MockSQLXRows {
	mock := &MockSQLXRows{ctrl: ctrl}
	mock.recorder = &MockSQLXRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLXRows) EXPECT() *MockSQLXRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSQLXRows) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLXRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLXRows)(nil).Close))
}

// ColumnTypes mocks base method.
func (m *MockSQLXRows) ColumnTypes() ([]*sql.ColumnType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ColumnTypes")
	ret0, _ := ret[0].([]*sql.ColumnType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ColumnTypes indicates an expected call of ColumnTypes.
func (mr *MockSQLXRowsMockRecorder) ColumnTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ColumnTypes", reflect.TypeOf((*MockSQLXRows)(nil).ColumnTypes))
}

// Columns mocks base method.
func (m *MockSQLXRows) Columns() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Columns")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Columns indicates an expected call of Columns.
func (mr *MockSQLXRowsMockRecorder) Columns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Columns", reflect.TypeOf((*MockSQLXRows)(nil).Columns))
}

// Err mocks base method.
func (m *MockSQLXRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockSQLXRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSQLXRows)(nil).Err))
}

// MapScan mocks base method.
func (m *MockSQLXRows) MapScan(dest map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapScan", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// MapScan indicates an expected call of MapScan.
func (mr *MockSQLXRowsMockRecorder) MapScan(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapScan", reflect.TypeOf((*MockSQLXRows)(nil).MapScan), dest)
}

// Next mocks base method.
func (m *MockSQLXRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockSQLXRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSQLXRows)(nil).Next))
}

// NextResultSet mocks base method.
func (m *MockSQLXRows) NextResultSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextResultSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NextResultSet indicates an expected call of NextResultSet.
func (mr *MockSQLXRowsMockRecorder) NextResultSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextResultSet", reflect.TypeOf((*MockSQLXRows)(nil).NextResultSet))
}

// Scan mocks base method.
func (m *MockSQLXRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockSQLXRowsMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockSQLXRows)(nil).Scan), dest...)
}

// SliceScan mocks base method.
func (m *MockSQLXRows) SliceScan() ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliceScan")
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SliceScan indicates an expected call of SliceScan.
func (mr *MockSQLXRowsMockRecorder) SliceScan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliceScan", reflect.TypeOf((*MockSQLXRows)(nil).SliceScan))
}

// StructScan mocks base method.
func (m *MockSQLXRows) StructScan(dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructScan", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// StructScan indicates an expected call of StructScan.
func (mr *MockSQLXRowsMockRecorder) StructScan(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructScan", reflect.TypeOf((*MockSQLXRows)(nil).StructScan), dest)
}

// MockSQLXClient is a mock of SQLXClient interface.
type MockSQLXClient struct {
	ctrl     *gomock.Controller
	recorder *MockSQLXClientMockRecorder
}

// MockSQLXClientMockRecorder is the mock recorder for MockSQLXClient.
type MockSQLXClientMockRecorder struct {
	mock *MockSQLXClient
}

// NewMockSQLXClient creates a new mock instance.
func NewMockSQLXClient(ctrl *gomock.Controller) *MockSQLXClient {
	mock := &MockSQLXClient{ctrl: ctrl}
	mock.recorder = &MockSQLXClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLXClient) EXPECT() *MockSQLXClientMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockSQLXClient) BeginTransaction(ctx context.Context, opts *sql.TxOptions) (contracts.SQLXTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, opts)
	ret0, _ := ret[0].(contracts.SQLXTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockSQLXClientMockRecorder) BeginTransaction(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockSQLXClient)(nil).BeginTransaction), ctx, opts)
}

// Close mocks base method.
func (m *MockSQLXClient) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLXClientMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLXClient)(nil).Close), ctx)
}

// Logger mocks base method.
func (m *MockSQLXClient) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSQLXClientMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSQLXClient)(nil).Logger))
}

// Name mocks base method.
func (m *MockSQLXClient) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSQLXClientMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSQLXClient)(nil).Name))
}

// NamedExec mocks base method.
func (m *MockSQLXClient) NamedExec(ctx context.Context, query string, args map[string]any) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedExec", ctx, query, args)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedExec indicates an expected call of NamedExec.
func (mr *MockSQLXClientMockRecorder) NamedExec(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedExec", reflect.TypeOf((*MockSQLXClient)(nil).NamedExec), ctx, query, args)
}

// NamedGet mocks base method.
func (m *MockSQLXClient) NamedGet(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedGet", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedGet indicates an expected call of NamedGet.
func (mr *MockSQLXClientMockRecorder) NamedGet(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedGet", reflect.TypeOf((*MockSQLXClient)(nil).NamedGet), ctx, dest, query, args)
}

// NamedQuery mocks base method.
func (m *MockSQLXClient) NamedQuery(ctx context.Context, query string, args map[string]any) (contracts.SQLXRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedQuery", ctx, query, args)
	ret0, _ := ret[0].(contracts.SQLXRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedQuery indicates an expected call of NamedQuery.
func (mr *MockSQLXClientMockRecorder) NamedQuery(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedQuery", reflect.TypeOf((*MockSQLXClient)(nil).NamedQuery), ctx, query, args)
}

// NamedSelect mocks base method.
func (m *MockSQLXClient) NamedSelect(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedSelect", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedSelect indicates an expected call of NamedSelect.
func (mr *MockSQLXClientMockRecorder) NamedSelect(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedSelect", reflect.TypeOf((*MockSQLXClient)(nil).NamedSelect), ctx, dest, query, args)
}

// Ping mocks base method.
func (m *MockSQLXClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLXClientMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLXClient)(nil).Ping), ctx)
}

// Type mocks base method.
func (m *MockSQLXClient) Type() sqlclienttype.SqlClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(sqlclienttype.SqlClientType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSQLXClientMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSQLXClient)(nil).Type))
}

// MockSQLXClientAdapter is a mock of SQLXClientAdapter interface.
type MockSQLXClientAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSQLXClientAdapterMockRecorder
}

// MockSQLXClientAdapterMockRecorder is the mock recorder for MockSQLXClientAdapter.
type MockSQLXClientAdapterMockRecorder struct {
	mock *MockSQLXClientAdapter
}

// NewMockSQLXClientAdapter creates a new mock instance.
func NewMockSQLXClientAdapter(ctrl *gomock.Controller) *MockSQLXClientAdapter {
	mock := &MockSQLXClientAdapter{ctrl: ctrl}
	mock.recorder = &MockSQLXClientAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLXClientAdapter) EXPECT() *MockSQLXClientAdapterMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockSQLXClientAdapter) BeginTransaction(ctx context.Context, opts *sql.TxOptions) (contracts.SQLXTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, opts)
	ret0, _ := ret[0].(contracts.SQLXTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockSQLXClientAdapterMockRecorder) BeginTransaction(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockSQLXClientAdapter)(nil).BeginTransaction), ctx, opts)
}

// Close mocks base method.
func (m *MockSQLXClientAdapter) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLXClientAdapterMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQLXClientAdapter)(nil).Close), ctx)
}

// Logger mocks base method.
func (m *MockSQLXClientAdapter) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSQLXClientAdapterMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSQLXClientAdapter)(nil).Logger))
}

// Name mocks base method.
func (m *MockSQLXClientAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSQLXClientAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSQLXClientAdapter)(nil).Name))
}

// NamedExec mocks base method.
func (m *MockSQLXClientAdapter) NamedExec(ctx context.Context, query string, args map[string]any) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedExec", ctx, query, args)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedExec indicates an expected call of NamedExec.
func (mr *MockSQLXClientAdapterMockRecorder) NamedExec(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedExec", reflect.TypeOf((*MockSQLXClientAdapter)(nil).NamedExec), ctx, query, args)
}

// NamedGet mocks base method.
func (m *MockSQLXClientAdapter) NamedGet(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedGet", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedGet indicates an expected call of NamedGet.
func (mr *MockSQLXClientAdapterMockRecorder) NamedGet(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedGet", reflect.TypeOf((*MockSQLXClientAdapter)(nil).NamedGet), ctx, dest, query, args)
}

// NamedQuery mocks base method.
func (m *MockSQLXClientAdapter) NamedQuery(ctx context.Context, query string, args map[string]any) (contracts.SQLXRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedQuery", ctx, query, args)
	ret0, _ := ret[0].(contracts.SQLXRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedQuery indicates an expected call of NamedQuery.
func (mr *MockSQLXClientAdapterMockRecorder) NamedQuery(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedQuery", reflect.TypeOf((*MockSQLXClientAdapter)(nil).NamedQuery), ctx, query, args)
}

// NamedSelect mocks base method.
func (m *MockSQLXClientAdapter) NamedSelect(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedSelect", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedSelect indicates an expected call of NamedSelect.
func (mr *MockSQLXClientAdapterMockRecorder) NamedSelect(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedSelect", reflect.TypeOf((*MockSQLXClientAdapter)(nil).NamedSelect), ctx, dest, query, args)
}

// Ping mocks base method.
func (m *MockSQLXClientAdapter) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLXClientAdapterMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLXClientAdapter)(nil).Ping), ctx)
}

// Type mocks base method.
func (m *MockSQLXClientAdapter) Type() sqlclienttype.SqlClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(sqlclienttype.SqlClientType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockSQLXClientAdapterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSQLXClientAdapter)(nil).Type))
}

// MockSQLXTransaction is a mock of SQLXTransaction interface.
type MockSQLXTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockSQLXTransactionMockRecorder
}

// MockSQLXTransactionMockRecorder is the mock recorder for MockSQLXTransaction.
type MockSQLXTransactionMockRecorder struct {
	mock *MockSQLXTransaction
}

// NewMockSQLXTransaction creates a new mock instance.
func NewMockSQLXTransaction(ctrl *gomock.Controller) *MockSQLXTransaction {
	mock := &MockSQLXTransaction{ctrl: ctrl}
	mock.recorder = &MockSQLXTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLXTransaction) EXPECT() *MockSQLXTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockSQLXTransaction) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockSQLXTransactionMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockSQLXTransaction)(nil).Commit), ctx)
}

// NamedExec mocks base method.
func (m *MockSQLXTransaction) NamedExec(ctx context.Context, query string, args map[string]any) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedExec", ctx, query, args)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedExec indicates an expected call of NamedExec.
func (mr *MockSQLXTransactionMockRecorder) NamedExec(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedExec", reflect.TypeOf((*MockSQLXTransaction)(nil).NamedExec), ctx, query, args)
}

// NamedGet mocks base method.
func (m *MockSQLXTransaction) NamedGet(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedGet", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedGet indicates an expected call of NamedGet.
func (mr *MockSQLXTransactionMockRecorder) NamedGet(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedGet", reflect.TypeOf((*MockSQLXTransaction)(nil).NamedGet), ctx, dest, query, args)
}

// NamedQuery mocks base method.
func (m *MockSQLXTransaction) NamedQuery(ctx context.Context, query string, args map[string]any) (contracts.SQLXRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedQuery", ctx, query, args)
	ret0, _ := ret[0].(contracts.SQLXRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedQuery indicates an expected call of NamedQuery.
func (mr *MockSQLXTransactionMockRecorder) NamedQuery(ctx, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedQuery", reflect.TypeOf((*MockSQLXTransaction)(nil).NamedQuery), ctx, query, args)
}

// NamedSelect mocks base method.
func (m *MockSQLXTransaction) NamedSelect(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedSelect", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedSelect indicates an expected call of NamedSelect.
func (mr *MockSQLXTransactionMockRecorder) NamedSelect(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedSelect", reflect.TypeOf((*MockSQLXTransaction)(nil).NamedSelect), ctx, dest, query, args)
}

// Rollback mocks base method.
func (m *MockSQLXTransaction) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockSQLXTransactionMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockSQLXTransaction)(nil).Rollback), ctx)
}

// MockWithDBGetter is a mock of WithDBGetter interface.
type MockWithDBGetter struct {
	ctrl     *gomock.Controller
	recorder *MockWithDBGetterMockRecorder
}

// MockWithDBGetterMockRecorder is the mock recorder for MockWithDBGetter.
type MockWithDBGetterMockRecorder struct {
	mock *MockWithDBGetter
}

// NewMockWithDBGetter creates a new mock instance.
func NewMockWithDBGetter(ctrl *gomock.Controller) *MockWithDBGetter {
	mock := &MockWithDBGetter{ctrl: ctrl}
	mock.recorder = &MockWithDBGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithDBGetter) EXPECT() *MockWithDBGetterMockRecorder {
	return m.recorder
}

// DB mocks base method.
func (m *MockWithDBGetter) DB() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockWithDBGetterMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockWithDBGetter)(nil).DB))
}
