// @generated by protoc-gen-es v2.12.0
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export declare const file_common_v1_common: GenFile;

/**
 * @generated from message common.v1.PaginationRequest
 */
export declare type PaginationRequest = Message<"common.v1.PaginationRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 page_size = 2;
   */
  pageSize: bigint;
};

/**
 * Describes the message common.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export declare const PaginationRequestSchema: GenMessage<PaginationRequest>;

/**
 * @generated from message common.v1.PaginationResponse
 */
export declare type PaginationResponse = Message<"common.v1.PaginationResponse"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 page_size = 2;
   */
  pageSize: bigint;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;

  /**
   * @generated from field: int64 page_count = 4;
   */
  pageCount: bigint;
};

/**
 * Describes the message common.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export declare const PaginationResponseSchema: GenMessage<PaginationResponse>;

