// @generated by protoc-gen-es v2.12.0
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEgljb21tb24udjEiPgoRUGFnaW5hdGlvblJlcXVlc3QSEQoEcGFnZRgBIAEoA0ID4EECEhYKCXBhZ2Vfc2l6ZRgCIAEoA0ID4EECIl4KElBhZ2luYXRpb25SZXNwb25zZRIMCgRwYWdlGAEgASgDEhEKCXBhZ2Vfc2l6ZRgCIAEoAxITCgt0b3RhbF9jb3VudBgDIAEoAxISCgpwYWdlX2NvdW50GAQgASgDQlRaUmZyaXNib28tYmFuay9vcGVuYXBpLWdlbmVyYXRvci1zZXJ2aWNlL2ludGVybmFsL3NoYXJlZC9ncnBjL2dlbi9jb21tb24vdjE7Y29tbW9udjFiBnByb3RvMw", [file_google_api_field_behavior]);

/**
 * Describes the message common.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

/**
 * Describes the message common.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema = /*@__PURE__*/
  messageDesc(file_common_v1_common, 1);

