// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./testdata/enums/test_enum/test_enum.go

package testenum

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// TestEnum is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type TestEnum struct {
	testEnum
}

// testEnumsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the TestEnum type.
type testEnumsContainer struct {
	UNKNOWN   TestEnum
	PASSED    TestEnum
	SKIPPED   TestEnum
	SCHEDULED TestEnum
	RUNNING   TestEnum
	BOOKED    TestEnum
}

// TestEnums is a main entry point using the TestEnum type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var TestEnums = testEnumsContainer{
	UNKNOWN: TestEnum{
		testEnum: unknown,
	},
	PASSED: TestEnum{
		testEnum: passed,
	},
	SKIPPED: TestEnum{
		testEnum: skipped,
	},
	SCHEDULED: TestEnum{
		testEnum: scheduled,
	},
	RUNNING: TestEnum{
		testEnum: running,
	},
	BOOKED: TestEnum{
		testEnum: booked,
	},
}

// invalidTestEnum is an invalid sentinel value for TestEnum
var invalidTestEnum = TestEnum{
	testEnum: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t testEnumsContainer) allSlice() []TestEnum {
	return []TestEnum{
		TestEnums.PASSED,
		TestEnums.SKIPPED,
		TestEnums.SCHEDULED,
		TestEnums.RUNNING,
		TestEnums.BOOKED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t testEnumsContainer) All() iter.Seq[TestEnum] {
	return func(yield func(TestEnum) bool) {
		for _, v := range t.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseTestEnum = errors.New("invalid input provided to parse to TestEnum")

// ParseTestEnum parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseTestEnum(input any) (TestEnum, error) {
	switch v := input.(type) {
	case TestEnum:
		return v, nil
	case string:
		if result := stringToTestEnum(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToTestEnum(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToTestEnum(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToTestEnum(v); result != nil {
			return *result, nil
		}
	default:
		return invalidTestEnum, fmt.Errorf("invalid type %T", input)
	}
	return invalidTestEnum, fmt.Errorf("%w: invalid value %v", ErrParseTestEnum, input)
}

// testEnumsNameMap is a map of enum values to their TestEnum representation
// It is used to convert string representations of enum values into their TestEnum representation.
var testEnumsNameMap = map[string]TestEnum{
	"unknown":   TestEnums.UNKNOWN,
	"passed":    TestEnums.PASSED,
	"skipped":   TestEnums.SKIPPED,
	"scheduled": TestEnums.SCHEDULED,
	"running":   TestEnums.RUNNING,
	"booked":    TestEnums.BOOKED,
}

// stringToTestEnum converts a string representation of an enum value into its TestEnum representation
// It returns a pointer to the TestEnum representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToTestEnum(s string) *TestEnum {
	if t, ok := testEnumsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToTestEnum converts a numeric value to a TestEnum
// It returns a pointer to the TestEnum representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToTestEnum[T number](num T) *TestEnum {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(TestEnums.allSlice()) {
		return nil
	}
	result := TestEnums.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveTestEnums iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveTestEnums(f func(TestEnum)) {
	for _, p := range TestEnums.allSlice() {
		f(p)
	}
}

// validTestEnums is a map of enum values to their validity
var validTestEnums = map[TestEnum]bool{
	TestEnums.UNKNOWN:   false,
	TestEnums.PASSED:    true,
	TestEnums.SKIPPED:   true,
	TestEnums.SCHEDULED: true,
	TestEnums.RUNNING:   true,
	TestEnums.BOOKED:    true,
}

// IsValid checks whether the TestEnums value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (t TestEnum) IsValid() bool {
	return validTestEnums[t]
}

// MarshalJSON implements the json.Marshaler interface for TestEnum.
// It returns the JSON representation of the enum value as a byte slice.
func (t TestEnum) MarshalJSON() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestEnum.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (t *TestEnum) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newt, err := ParseTestEnum(b)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for TestEnum.
// It returns the string representation of the enum value as a byte slice
func (t TestEnum) MarshalText() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TestEnum.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TestEnum) UnmarshalText(b []byte) error {
	newt, err := ParseTestEnum(b)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Scan implements the database/sql.Scanner interface for TestEnum.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (t *TestEnum) Scan(value any) error {
	newt, err := ParseTestEnum(value)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Value implements the database/sql/driver.Valuer interface for TestEnum.
// It returns the string representation of the enum value.
func (t TestEnum) Value() (driver.Value, error) {
	return t.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for TestEnum.
// It returns the binary representation of the enum value as a byte slice.
func (t TestEnum) MarshalBinary() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for TestEnum.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TestEnum) UnmarshalBinary(b []byte) error {
	newt, err := ParseTestEnum(b)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for TestEnum.
// It returns the string representation of the enum value.
func (t TestEnum) MarshalYAML() ([]byte, error) {
	return []byte(t.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (t *TestEnum) UnmarshalYAML(b []byte) error {
	newt, err := ParseTestEnum(b)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// testenumNames is a constant string slice containing all enum values cononical absolute names
const testenumNames = "unknownpassedskippedscheduledrunningbooked"

// testenumNamesMap is a map of enum values to their canonical absolute
// name positions within the testenumNames string slice
var testenumNamesMap = map[TestEnum]string{
	TestEnums.UNKNOWN:   testenumNames[0:7],
	TestEnums.PASSED:    testenumNames[7:13],
	TestEnums.SKIPPED:   testenumNames[13:20],
	TestEnums.SCHEDULED: testenumNames[20:29],
	TestEnums.RUNNING:   testenumNames[29:36],
	TestEnums.BOOKED:    testenumNames[36:42],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (t TestEnum) String() string {
	if str, ok := testenumNamesMap[t]; ok {
		return str
	}
	return fmt.Sprintf("testenum(%d)", t.testEnum)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [6]struct{}
	_ = x[unknown]
	_ = x[passed-1]
	_ = x[skipped-2]
	_ = x[scheduled-3]
	_ = x[running-4]
	_ = x[booked-5]
}
