// @generated by protoc-gen-es v2.12.0
// @generated from file entity/v1/entity_service.proto (package entity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { PaginationRequest, PaginationResponse } from "../../query/v1/pagination_pb";
import type { QueryFilters } from "../../query/v1/filter_pb";
import type { QueryOrders } from "../../query/v1/order_pb";
import type { QuerySearches } from "../../query/v1/search_pb";
import type { Entity } from "./entity_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/v1/entity_service.proto.
 */
export declare const file_entity_v1_entity_service: GenFile;

/**
 * ---------- List ----------
 *
 * @generated from message entity.v1.ListEntitiesRequest
 */
export declare type ListEntitiesRequest = Message<"entity.v1.ListEntitiesRequest"> & {
  /**
   * @generated from field: entity.v1.ListEntitiesRequest.Body body = 1;
   */
  body?: ListEntitiesRequest_Body | undefined;
};

/**
 * Describes the message entity.v1.ListEntitiesRequest.
 * Use `create(ListEntitiesRequestSchema)` to create a new message.
 */
export declare const ListEntitiesRequestSchema: GenMessage<ListEntitiesRequest>;

/**
 * @generated from message entity.v1.ListEntitiesRequest.Body
 */
export declare type ListEntitiesRequest_Body = Message<"entity.v1.ListEntitiesRequest.Body"> & {
  /**
   * @generated from field: query.v1.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest | undefined;

  /**
   * @generated from field: query.v1.QueryFilters filters = 2;
   */
  filters?: QueryFilters | undefined;

  /**
   * @generated from field: query.v1.QueryOrders orders = 3;
   */
  orders?: QueryOrders | undefined;

  /**
   * @generated from field: query.v1.QuerySearches searches = 4;
   */
  searches?: QuerySearches | undefined;
};

/**
 * Describes the message entity.v1.ListEntitiesRequest.Body.
 * Use `create(ListEntitiesRequest_BodySchema)` to create a new message.
 */
export declare const ListEntitiesRequest_BodySchema: GenMessage<ListEntitiesRequest_Body>;

/**
 * @generated from message entity.v1.ListEntitiesResponse
 */
export declare type ListEntitiesResponse = Message<"entity.v1.ListEntitiesResponse"> & {
  /**
   * @generated from field: entity.v1.ListEntitiesResponse.Data data = 1;
   */
  data?: ListEntitiesResponse_Data | undefined;
};

/**
 * Describes the message entity.v1.ListEntitiesResponse.
 * Use `create(ListEntitiesResponseSchema)` to create a new message.
 */
export declare const ListEntitiesResponseSchema: GenMessage<ListEntitiesResponse>;

/**
 * @generated from message entity.v1.ListEntitiesResponse.Data
 */
export declare type ListEntitiesResponse_Data = Message<"entity.v1.ListEntitiesResponse.Data"> & {
  /**
   * @generated from field: repeated entity.v1.Entity entities = 1;
   */
  entities: Entity[];

  /**
   * @generated from field: query.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse | undefined;
};

/**
 * Describes the message entity.v1.ListEntitiesResponse.Data.
 * Use `create(ListEntitiesResponse_DataSchema)` to create a new message.
 */
export declare const ListEntitiesResponse_DataSchema: GenMessage<ListEntitiesResponse_Data>;

/**
 * ---------- Get by Slug ----------
 *
 * @generated from message entity.v1.GetEntityBySlugRequest
 */
export declare type GetEntityBySlugRequest = Message<"entity.v1.GetEntityBySlugRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: optional bool include_hidden = 2;
   */
  includeHidden?: boolean | undefined;
};

/**
 * Describes the message entity.v1.GetEntityBySlugRequest.
 * Use `create(GetEntityBySlugRequestSchema)` to create a new message.
 */
export declare const GetEntityBySlugRequestSchema: GenMessage<GetEntityBySlugRequest>;

/**
 * @generated from message entity.v1.GetEntityBySlugResponse
 */
export declare type GetEntityBySlugResponse = Message<"entity.v1.GetEntityBySlugResponse"> & {
  /**
   * @generated from field: entity.v1.GetEntityBySlugResponse.Data data = 1;
   */
  data?: GetEntityBySlugResponse_Data | undefined;
};

/**
 * Describes the message entity.v1.GetEntityBySlugResponse.
 * Use `create(GetEntityBySlugResponseSchema)` to create a new message.
 */
export declare const GetEntityBySlugResponseSchema: GenMessage<GetEntityBySlugResponse>;

/**
 * @generated from message entity.v1.GetEntityBySlugResponse.Data
 */
export declare type GetEntityBySlugResponse_Data = Message<"entity.v1.GetEntityBySlugResponse.Data"> & {
  /**
   * @generated from field: entity.v1.Entity entity = 1;
   */
  entity?: Entity | undefined;
};

/**
 * Describes the message entity.v1.GetEntityBySlugResponse.Data.
 * Use `create(GetEntityBySlugResponse_DataSchema)` to create a new message.
 */
export declare const GetEntityBySlugResponse_DataSchema: GenMessage<GetEntityBySlugResponse_Data>;

/**
 * ---------- Create ----------
 *
 * @generated from message entity.v1.CreateEntityRequest
 */
export declare type CreateEntityRequest = Message<"entity.v1.CreateEntityRequest"> & {
  /**
   * @generated from field: entity.v1.CreateEntityRequest.Body body = 1;
   */
  body?: CreateEntityRequest_Body | undefined;
};

/**
 * Describes the message entity.v1.CreateEntityRequest.
 * Use `create(CreateEntityRequestSchema)` to create a new message.
 */
export declare const CreateEntityRequestSchema: GenMessage<CreateEntityRequest>;

/**
 * @generated from message entity.v1.CreateEntityRequest.Payload
 */
export declare type CreateEntityRequest_Payload = Message<"entity.v1.CreateEntityRequest.Payload"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string | undefined;
};

/**
 * Describes the message entity.v1.CreateEntityRequest.Payload.
 * Use `create(CreateEntityRequest_PayloadSchema)` to create a new message.
 */
export declare const CreateEntityRequest_PayloadSchema: GenMessage<CreateEntityRequest_Payload>;

/**
 * @generated from message entity.v1.CreateEntityRequest.Body
 */
export declare type CreateEntityRequest_Body = Message<"entity.v1.CreateEntityRequest.Body"> & {
  /**
   * @generated from field: entity.v1.CreateEntityRequest.Payload payload = 1;
   */
  payload?: CreateEntityRequest_Payload | undefined;
};

/**
 * Describes the message entity.v1.CreateEntityRequest.Body.
 * Use `create(CreateEntityRequest_BodySchema)` to create a new message.
 */
export declare const CreateEntityRequest_BodySchema: GenMessage<CreateEntityRequest_Body>;

/**
 * @generated from message entity.v1.CreateEntityResponse
 */
export declare type CreateEntityResponse = Message<"entity.v1.CreateEntityResponse"> & {
  /**
   * @generated from field: entity.v1.CreateEntityResponse.Data data = 1;
   */
  data?: CreateEntityResponse_Data | undefined;
};

/**
 * Describes the message entity.v1.CreateEntityResponse.
 * Use `create(CreateEntityResponseSchema)` to create a new message.
 */
export declare const CreateEntityResponseSchema: GenMessage<CreateEntityResponse>;

/**
 * @generated from message entity.v1.CreateEntityResponse.Data
 */
export declare type CreateEntityResponse_Data = Message<"entity.v1.CreateEntityResponse.Data"> & {
  /**
   * @generated from field: entity.v1.Entity entity = 1;
   */
  entity?: Entity | undefined;
};

/**
 * Describes the message entity.v1.CreateEntityResponse.Data.
 * Use `create(CreateEntityResponse_DataSchema)` to create a new message.
 */
export declare const CreateEntityResponse_DataSchema: GenMessage<CreateEntityResponse_Data>;

/**
 * ---------- Update ----------
 *
 * @generated from message entity.v1.UpdateEntityRequest
 */
export declare type UpdateEntityRequest = Message<"entity.v1.UpdateEntityRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: int64 version_lock = 2;
   */
  versionLock: bigint;

  /**
   * @generated from field: entity.v1.UpdateEntityRequest.Body body = 3;
   */
  body?: UpdateEntityRequest_Body | undefined;
};

/**
 * Describes the message entity.v1.UpdateEntityRequest.
 * Use `create(UpdateEntityRequestSchema)` to create a new message.
 */
export declare const UpdateEntityRequestSchema: GenMessage<UpdateEntityRequest>;

/**
 * @generated from message entity.v1.UpdateEntityRequest.Payload
 */
export declare type UpdateEntityRequest_Payload = Message<"entity.v1.UpdateEntityRequest.Payload"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string | undefined;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string | undefined;
};

/**
 * Describes the message entity.v1.UpdateEntityRequest.Payload.
 * Use `create(UpdateEntityRequest_PayloadSchema)` to create a new message.
 */
export declare const UpdateEntityRequest_PayloadSchema: GenMessage<UpdateEntityRequest_Payload>;

/**
 * @generated from message entity.v1.UpdateEntityRequest.Body
 */
export declare type UpdateEntityRequest_Body = Message<"entity.v1.UpdateEntityRequest.Body"> & {
  /**
   * @generated from field: entity.v1.UpdateEntityRequest.Payload payload = 1;
   */
  payload?: UpdateEntityRequest_Payload | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message entity.v1.UpdateEntityRequest.Body.
 * Use `create(UpdateEntityRequest_BodySchema)` to create a new message.
 */
export declare const UpdateEntityRequest_BodySchema: GenMessage<UpdateEntityRequest_Body>;

/**
 * @generated from message entity.v1.UpdateEntityResponse
 */
export declare type UpdateEntityResponse = Message<"entity.v1.UpdateEntityResponse"> & {
  /**
   * @generated from field: entity.v1.UpdateEntityResponse.Data data = 1;
   */
  data?: UpdateEntityResponse_Data | undefined;
};

/**
 * Describes the message entity.v1.UpdateEntityResponse.
 * Use `create(UpdateEntityResponseSchema)` to create a new message.
 */
export declare const UpdateEntityResponseSchema: GenMessage<UpdateEntityResponse>;

/**
 * @generated from message entity.v1.UpdateEntityResponse.Data
 */
export declare type UpdateEntityResponse_Data = Message<"entity.v1.UpdateEntityResponse.Data"> & {
  /**
   * @generated from field: entity.v1.Entity entity = 1;
   */
  entity?: Entity | undefined;
};

/**
 * Describes the message entity.v1.UpdateEntityResponse.Data.
 * Use `create(UpdateEntityResponse_DataSchema)` to create a new message.
 */
export declare const UpdateEntityResponse_DataSchema: GenMessage<UpdateEntityResponse_Data>;

/**
 * ---------- Delete ----------
 *
 * @generated from message entity.v1.DeleteEntityRequest
 */
export declare type DeleteEntityRequest = Message<"entity.v1.DeleteEntityRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: int64 version_lock = 2;
   */
  versionLock: bigint;
};

/**
 * Describes the message entity.v1.DeleteEntityRequest.
 * Use `create(DeleteEntityRequestSchema)` to create a new message.
 */
export declare const DeleteEntityRequestSchema: GenMessage<DeleteEntityRequest>;

/**
 * @generated from message entity.v1.DeleteEntityResponse
 */
export declare type DeleteEntityResponse = Message<"entity.v1.DeleteEntityResponse"> & {
  /**
   * @generated from field: entity.v1.DeleteEntityResponse.Data data = 1;
   */
  data?: DeleteEntityResponse_Data | undefined;
};

/**
 * Describes the message entity.v1.DeleteEntityResponse.
 * Use `create(DeleteEntityResponseSchema)` to create a new message.
 */
export declare const DeleteEntityResponseSchema: GenMessage<DeleteEntityResponse>;

/**
 * @generated from message entity.v1.DeleteEntityResponse.Data
 */
export declare type DeleteEntityResponse_Data = Message<"entity.v1.DeleteEntityResponse.Data"> & {
  /**
   * @generated from field: entity.v1.Entity entity = 1;
   */
  entity?: Entity | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 2;
   */
  deletedAt?: Timestamp | undefined;

  /**
   * @generated from field: bool was_permanent = 3;
   */
  wasPermanent: boolean;
};

/**
 * Describes the message entity.v1.DeleteEntityResponse.Data.
 * Use `create(DeleteEntityResponse_DataSchema)` to create a new message.
 */
export declare const DeleteEntityResponse_DataSchema: GenMessage<DeleteEntityResponse_Data>;

/**
 * ---------- Service ----------
 *
 * @generated from service entity.v1.EntityService
 */
export declare const EntityService: GenService<{
  /**
   * @generated from rpc entity.v1.EntityService.ListEntities
   */
  listEntities: {
    methodKind: "unary";
    input: typeof ListEntitiesRequestSchema;
    output: typeof ListEntitiesResponseSchema;
  },
  /**
   * @generated from rpc entity.v1.EntityService.GetEntityBySlug
   */
  getEntityBySlug: {
    methodKind: "unary";
    input: typeof GetEntityBySlugRequestSchema;
    output: typeof GetEntityBySlugResponseSchema;
  },
  /**
   * @generated from rpc entity.v1.EntityService.CreateEntity
   */
  createEntity: {
    methodKind: "unary";
    input: typeof CreateEntityRequestSchema;
    output: typeof CreateEntityResponseSchema;
  },
  /**
   * @generated from rpc entity.v1.EntityService.UpdateEntity
   */
  updateEntity: {
    methodKind: "unary";
    input: typeof UpdateEntityRequestSchema;
    output: typeof UpdateEntityResponseSchema;
  },
  /**
   * @generated from rpc entity.v1.EntityService.DeleteEntity
   */
  deleteEntity: {
    methodKind: "unary";
    input: typeof DeleteEntityRequestSchema;
    output: typeof DeleteEntityResponseSchema;
  },
}>;

