// @generated by protoc-gen-es v2.12.0
// @generated from file entity/v1/entity.proto (package entity.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/v1/entity.proto.
 */
export const file_entity_v1_entity = /*@__PURE__*/
  fileDesc("ChZlbnRpdHkvdjEvZW50aXR5LnByb3RvEgllbnRpdHkudjEi8wEKBkVudGl0eRIMCgRzbHVnGAEgASgJEgwKBG5hbWUYAiABKAkSGAoLZGVzY3JpcHRpb24YAyABKAlIAIgBARIUCgx2ZXJzaW9uX2xvY2sYBCABKAMSLQoJaGlkZGVuX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpjcmVhdGVkX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIOCgxfZGVzY3JpcHRpb25CVFpSZnJpc2Jvby1iYW5rL29wZW5hcGktZ2VuZXJhdG9yLXNlcnZpY2UvaW50ZXJuYWwvc2hhcmVkL2dycGMvZ2VuL2VudGl0eS92MTtlbnRpdHl2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message entity.v1.Entity.
 * Use `create(EntitySchema)` to create a new message.
 */
export const EntitySchema = /*@__PURE__*/
  messageDesc(file_entity_v1_entity, 0);

