// @generated by protoc-gen-connect-query v2.2.0
// @generated from file entity/v1/entity_service.proto (package entity.v1, syntax proto3)
/* eslint-disable */

import { EntityService } from "./entity_service_pb";

/**
 * @generated from rpc entity.v1.EntityService.ListEntities
 */
export const listEntities: typeof EntityService["method"]["listEntities"];
/**
 * @generated from rpc entity.v1.EntityService.GetEntityBySlug
 */
export const getEntityBySlug: typeof EntityService["method"]["getEntityBySlug"];
/**
 * @generated from rpc entity.v1.EntityService.CreateEntity
 */
export const createEntity: typeof EntityService["method"]["createEntity"];
/**
 * @generated from rpc entity.v1.EntityService.UpdateEntity
 */
export const updateEntity: typeof EntityService["method"]["updateEntity"];
/**
 * @generated from rpc entity.v1.EntityService.DeleteEntity
 */
export const deleteEntity: typeof EntityService["method"]["deleteEntity"];
