// @generated by protoc-gen-es v2.16.0
// @generated from file entity/v1/entity.proto (package entity.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/v1/entity.proto.
 */
export const file_entity_v1_entity = /*@__PURE__*/
  fileDesc("ChZlbnRpdHkvdjEvZW50aXR5LnByb3RvEgllbnRpdHkudjEi9AEKBkVudGl0eRIMCgRzbHVnGAEgASgJEgwKBG5hbWUYAiABKAkSGAoLZGVzY3JpcHRpb24YAyABKAlIAIgBARIUCgx2ZXJzaW9uX2xvY2sYBCABKAMSLgoKZGVsZXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKY3JlYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCDgoMX2Rlc2NyaXB0aW9uQlRaUmZyaXNib28tYmFuay9vcGVuYXBpLWdlbmVyYXRvci1zZXJ2aWNlL2ludGVybmFsL3NoYXJlZC9ncnBjL2dlbi9lbnRpdHkvdjE7ZW50aXR5djFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message entity.v1.Entity.
 * Use `create(EntitySchema)` to create a new message.
 */
export const EntitySchema = /*@__PURE__*/
  messageDesc(file_entity_v1_entity, 0);

