// @generated by protoc-gen-es v2.12.0
// @generated from file entity/v1/entity.proto (package entity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/v1/entity.proto.
 */
export declare const file_entity_v1_entity: GenFile;

/**
 * @generated from message entity.v1.Entity
 */
export declare type Entity = Message<"entity.v1.Entity"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string | undefined;

  /**
   * @generated from field: int64 version_lock = 4;
   */
  versionLock: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp hidden_at = 5;
   */
  hiddenAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message entity.v1.Entity.
 * Use `create(EntitySchema)` to create a new message.
 */
export declare const EntitySchema: GenMessage<Entity>;

