// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/filter_comparison/filter_comparison.go

package filtercomparison

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// FilterComparison is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type FilterComparison struct {
	filterComparison
}

// filterComparisonsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the FilterComparison type.
type filterComparisonsContainer struct {
	UNKNOWN        FilterComparison
	BETWEEN        FilterComparison
	EQUAL          FilterComparison
	GREATER        FilterComparison
	GREATEROREQUAL FilterComparison
	IN             FilterComparison
	LOWER          FilterComparison
	LOWEROREQUAL   FilterComparison
	NOTEQUAL       FilterComparison
	ISEMPTY        FilterComparison
	ISFALSE        FilterComparison
	ISNOTEMPTY     FilterComparison
	ISNOTFALSE     FilterComparison
	ISNOTNULL      FilterComparison
	ISNOTTRUE      FilterComparison
	ISNULL         FilterComparison
	ISTRUE         FilterComparison
	ISUNKNOWN      FilterComparison
}

// FilterComparisons is a main entry point using the FilterComparison type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var FilterComparisons = filterComparisonsContainer{
	UNKNOWN: FilterComparison{
		filterComparison: unknown,
	},
	BETWEEN: FilterComparison{
		filterComparison: between,
	},
	EQUAL: FilterComparison{
		filterComparison: equal,
	},
	GREATER: FilterComparison{
		filterComparison: greater,
	},
	GREATEROREQUAL: FilterComparison{
		filterComparison: greaterOrEqual,
	},
	IN: FilterComparison{
		filterComparison: in,
	},
	LOWER: FilterComparison{
		filterComparison: lower,
	},
	LOWEROREQUAL: FilterComparison{
		filterComparison: lowerOrEqual,
	},
	NOTEQUAL: FilterComparison{
		filterComparison: notEqual,
	},
	ISEMPTY: FilterComparison{
		filterComparison: isEmpty,
	},
	ISFALSE: FilterComparison{
		filterComparison: isFalse,
	},
	ISNOTEMPTY: FilterComparison{
		filterComparison: isNotEmpty,
	},
	ISNOTFALSE: FilterComparison{
		filterComparison: isNotFalse,
	},
	ISNOTNULL: FilterComparison{
		filterComparison: isNotNull,
	},
	ISNOTTRUE: FilterComparison{
		filterComparison: isNotTrue,
	},
	ISNULL: FilterComparison{
		filterComparison: isNull,
	},
	ISTRUE: FilterComparison{
		filterComparison: isTrue,
	},
	ISUNKNOWN: FilterComparison{
		filterComparison: isUnknown,
	},
}

// invalidFilterComparison is an invalid sentinel value for FilterComparison
var invalidFilterComparison = FilterComparison{
	filterComparison: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (f filterComparisonsContainer) allSlice() []FilterComparison {
	return []FilterComparison{
		FilterComparisons.BETWEEN,
		FilterComparisons.EQUAL,
		FilterComparisons.GREATER,
		FilterComparisons.GREATEROREQUAL,
		FilterComparisons.IN,
		FilterComparisons.LOWER,
		FilterComparisons.LOWEROREQUAL,
		FilterComparisons.NOTEQUAL,
		FilterComparisons.ISEMPTY,
		FilterComparisons.ISFALSE,
		FilterComparisons.ISNOTEMPTY,
		FilterComparisons.ISNOTFALSE,
		FilterComparisons.ISNOTNULL,
		FilterComparisons.ISNOTTRUE,
		FilterComparisons.ISNULL,
		FilterComparisons.ISTRUE,
		FilterComparisons.ISUNKNOWN,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (f filterComparisonsContainer) All() iter.Seq[FilterComparison] {
	return func(yield func(FilterComparison) bool) {
		for _, v := range f.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseFilterComparison = errors.New("invalid input provided to parse to FilterComparison")

// ParseFilterComparison parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseFilterComparison(input any) (FilterComparison, error) {
	switch v := input.(type) {
	case FilterComparison:
		return v, nil
	case string:
		if result := stringToFilterComparison(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToFilterComparison(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToFilterComparison(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToFilterComparison(v); result != nil {
			return *result, nil
		}
	default:
		return invalidFilterComparison, fmt.Errorf("invalid type %T", input)
	}
	return invalidFilterComparison, fmt.Errorf("%w: invalid value %v", ErrParseFilterComparison, input)
}

// filterComparisonsNameMap is a map of enum values to their FilterComparison representation
// It is used to convert string representations of enum values into their FilterComparison representation.
var filterComparisonsNameMap = map[string]FilterComparison{
	"unknown":        FilterComparisons.UNKNOWN,
	"between":        FilterComparisons.BETWEEN,
	"equal":          FilterComparisons.EQUAL,
	"greater":        FilterComparisons.GREATER,
	"greaterOrEqual": FilterComparisons.GREATEROREQUAL,
	"in":             FilterComparisons.IN,
	"lower":          FilterComparisons.LOWER,
	"lowerOrEqual":   FilterComparisons.LOWEROREQUAL,
	"notEqual":       FilterComparisons.NOTEQUAL,
	"isEmpty":        FilterComparisons.ISEMPTY,
	"isFalse":        FilterComparisons.ISFALSE,
	"isNotEmpty":     FilterComparisons.ISNOTEMPTY,
	"isNotFalse":     FilterComparisons.ISNOTFALSE,
	"isNotNull":      FilterComparisons.ISNOTNULL,
	"isNotTrue":      FilterComparisons.ISNOTTRUE,
	"isNull":         FilterComparisons.ISNULL,
	"isTrue":         FilterComparisons.ISTRUE,
	"isUnknown":      FilterComparisons.ISUNKNOWN,
}

// stringToFilterComparison converts a string representation of an enum value into its FilterComparison representation
// It returns a pointer to the FilterComparison representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToFilterComparison(s string) *FilterComparison {
	if t, ok := filterComparisonsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToFilterComparison converts a numeric value to a FilterComparison
// It returns a pointer to the FilterComparison representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToFilterComparison[T number](num T) *FilterComparison {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(FilterComparisons.allSlice()) {
		return nil
	}
	result := FilterComparisons.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveFilterComparisons iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveFilterComparisons(f func(FilterComparison)) {
	for _, p := range FilterComparisons.allSlice() {
		f(p)
	}
}

// validFilterComparisons is a map of enum values to their validity
var validFilterComparisons = map[FilterComparison]bool{
	FilterComparisons.UNKNOWN:        false,
	FilterComparisons.BETWEEN:        true,
	FilterComparisons.EQUAL:          true,
	FilterComparisons.GREATER:        true,
	FilterComparisons.GREATEROREQUAL: true,
	FilterComparisons.IN:             true,
	FilterComparisons.LOWER:          true,
	FilterComparisons.LOWEROREQUAL:   true,
	FilterComparisons.NOTEQUAL:       true,
	FilterComparisons.ISEMPTY:        true,
	FilterComparisons.ISFALSE:        true,
	FilterComparisons.ISNOTEMPTY:     true,
	FilterComparisons.ISNOTFALSE:     true,
	FilterComparisons.ISNOTNULL:      true,
	FilterComparisons.ISNOTTRUE:      true,
	FilterComparisons.ISNULL:         true,
	FilterComparisons.ISTRUE:         true,
	FilterComparisons.ISUNKNOWN:      true,
}

// IsValid checks whether the FilterComparisons value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (f FilterComparison) IsValid() bool {
	return validFilterComparisons[f]
}

// MarshalJSON implements the json.Marshaler interface for FilterComparison.
// It returns the JSON representation of the enum value as a byte slice.
func (f FilterComparison) MarshalJSON() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for FilterComparison.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (f *FilterComparison) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newf, err := ParseFilterComparison(b)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for FilterComparison.
// It returns the string representation of the enum value as a byte slice
func (f FilterComparison) MarshalText() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FilterComparison.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (f *FilterComparison) UnmarshalText(b []byte) error {
	newf, err := ParseFilterComparison(b)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// Scan implements the database/sql.Scanner interface for FilterComparison.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (f *FilterComparison) Scan(value any) error {
	newf, err := ParseFilterComparison(value)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// Value implements the database/sql/driver.Valuer interface for FilterComparison.
// It returns the string representation of the enum value.
func (f FilterComparison) Value() (driver.Value, error) {
	return f.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for FilterComparison.
// It returns the binary representation of the enum value as a byte slice.
func (f FilterComparison) MarshalBinary() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for FilterComparison.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (f *FilterComparison) UnmarshalBinary(b []byte) error {
	newf, err := ParseFilterComparison(b)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for FilterComparison.
// It returns the string representation of the enum value.
func (f FilterComparison) MarshalYAML() ([]byte, error) {
	return []byte(f.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (f *FilterComparison) UnmarshalYAML(b []byte) error {
	newf, err := ParseFilterComparison(b)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// filtercomparisonNames is a constant string slice containing all enum values cononical absolute names
const filtercomparisonNames = "unknownbetweenequalgreatergreaterOrEqualinlowerlowerOrEqualnotEqualisEmptyisFalseisNotEmptyisNotFalseisNotNullisNotTrueisNullisTrueisUnknown"

// filtercomparisonNamesMap is a map of enum values to their canonical absolute
// name positions within the filtercomparisonNames string slice
var filtercomparisonNamesMap = map[FilterComparison]string{
	FilterComparisons.UNKNOWN:        filtercomparisonNames[0:7],
	FilterComparisons.BETWEEN:        filtercomparisonNames[7:14],
	FilterComparisons.EQUAL:          filtercomparisonNames[14:19],
	FilterComparisons.GREATER:        filtercomparisonNames[19:26],
	FilterComparisons.GREATEROREQUAL: filtercomparisonNames[26:40],
	FilterComparisons.IN:             filtercomparisonNames[40:42],
	FilterComparisons.LOWER:          filtercomparisonNames[42:47],
	FilterComparisons.LOWEROREQUAL:   filtercomparisonNames[47:59],
	FilterComparisons.NOTEQUAL:       filtercomparisonNames[59:67],
	FilterComparisons.ISEMPTY:        filtercomparisonNames[67:74],
	FilterComparisons.ISFALSE:        filtercomparisonNames[74:81],
	FilterComparisons.ISNOTEMPTY:     filtercomparisonNames[81:91],
	FilterComparisons.ISNOTFALSE:     filtercomparisonNames[91:101],
	FilterComparisons.ISNOTNULL:      filtercomparisonNames[101:110],
	FilterComparisons.ISNOTTRUE:      filtercomparisonNames[110:119],
	FilterComparisons.ISNULL:         filtercomparisonNames[119:125],
	FilterComparisons.ISTRUE:         filtercomparisonNames[125:131],
	FilterComparisons.ISUNKNOWN:      filtercomparisonNames[131:140],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (f FilterComparison) String() string {
	if str, ok := filtercomparisonNamesMap[f]; ok {
		return str
	}
	return fmt.Sprintf("filtercomparison(%d)", f.filterComparison)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [18]struct{}
	_ = x[unknown]
	_ = x[between-1]
	_ = x[equal-2]
	_ = x[greater-3]
	_ = x[greaterOrEqual-4]
	_ = x[in-5]
	_ = x[lower-6]
	_ = x[lowerOrEqual-7]
	_ = x[notEqual-8]
	_ = x[isEmpty-9]
	_ = x[isFalse-10]
	_ = x[isNotEmpty-11]
	_ = x[isNotFalse-12]
	_ = x[isNotNull-13]
	_ = x[isNotTrue-14]
	_ = x[isNull-15]
	_ = x[isTrue-16]
	_ = x[isUnknown-17]
}
