// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/config/contracts/config_loader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	environment "frisboo-bank/openapi-generator-service/pkg/environment/models/enums/environment"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigLoader is a mock of ConfigLoader interface.
type MockConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLoaderMockRecorder
}

// MockConfigLoaderMockRecorder is the mock recorder for MockConfigLoader.
type MockConfigLoaderMockRecorder struct {
	mock *MockConfigLoader
}

// NewMockConfigLoader creates a new mock instance.
func NewMockConfigLoader(ctrl *gomock.Controller) *MockConfigLoader {
	mock := &MockConfigLoader{ctrl: ctrl}
	mock.recorder = &MockConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLoader) EXPECT() *MockConfigLoaderMockRecorder {
	return m.recorder
}

// HasKey mocks base method.
func (m *MockConfigLoader) HasKey(env environment.Environment, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasKey", env, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasKey indicates an expected call of HasKey.
func (mr *MockConfigLoaderMockRecorder) HasKey(env, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasKey", reflect.TypeOf((*MockConfigLoader)(nil).HasKey), env, key)
}

// Load mocks base method.
func (m *MockConfigLoader) Load(env environment.Environment, cfg any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", env, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockConfigLoaderMockRecorder) Load(env, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigLoader)(nil).Load), env, cfg)
}

// LoadKey mocks base method.
func (m *MockConfigLoader) LoadKey(env environment.Environment, cfg any, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadKey", env, cfg, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadKey indicates an expected call of LoadKey.
func (mr *MockConfigLoaderMockRecorder) LoadKey(env, cfg, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadKey", reflect.TypeOf((*MockConfigLoader)(nil).LoadKey), env, cfg, key)
}
