// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/order_direction/order_direction.go

package orderdirection

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// OrderDirection is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type OrderDirection struct {
	orderDirection
}

// orderDirectionsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the OrderDirection type.
type orderDirectionsContainer struct {
	UNKNOWN OrderDirection
	ASC     OrderDirection
	DESC    OrderDirection
}

// OrderDirections is a main entry point using the OrderDirection type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var OrderDirections = orderDirectionsContainer{
	UNKNOWN: OrderDirection{
		orderDirection: unknown,
	},
	ASC: OrderDirection{
		orderDirection: asc,
	},
	DESC: OrderDirection{
		orderDirection: desc,
	},
}

// invalidOrderDirection is an invalid sentinel value for OrderDirection
var invalidOrderDirection = OrderDirection{
	orderDirection: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o orderDirectionsContainer) allSlice() []OrderDirection {
	return []OrderDirection{
		OrderDirections.ASC,
		OrderDirections.DESC,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o orderDirectionsContainer) All() iter.Seq[OrderDirection] {
	return func(yield func(OrderDirection) bool) {
		for _, v := range o.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseOrderDirection = errors.New("invalid input provided to parse to OrderDirection")

// ParseOrderDirection parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseOrderDirection(input any) (OrderDirection, error) {
	switch v := input.(type) {
	case OrderDirection:
		return v, nil
	case string:
		if result := stringToOrderDirection(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToOrderDirection(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToOrderDirection(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToOrderDirection(v); result != nil {
			return *result, nil
		}
	default:
		return invalidOrderDirection, fmt.Errorf("invalid type %T", input)
	}
	return invalidOrderDirection, fmt.Errorf("%w: invalid value %v", ErrParseOrderDirection, input)
}

// orderDirectionsNameMap is a map of enum values to their OrderDirection representation
// It is used to convert string representations of enum values into their OrderDirection representation.
var orderDirectionsNameMap = map[string]OrderDirection{
	"unknown": OrderDirections.UNKNOWN,
	"asc":     OrderDirections.ASC,
	"desc":    OrderDirections.DESC,
}

// stringToOrderDirection converts a string representation of an enum value into its OrderDirection representation
// It returns a pointer to the OrderDirection representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToOrderDirection(s string) *OrderDirection {
	if t, ok := orderDirectionsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToOrderDirection converts a numeric value to a OrderDirection
// It returns a pointer to the OrderDirection representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToOrderDirection[T number](num T) *OrderDirection {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(OrderDirections.allSlice()) {
		return nil
	}
	result := OrderDirections.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveOrderDirections iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveOrderDirections(f func(OrderDirection)) {
	for _, p := range OrderDirections.allSlice() {
		f(p)
	}
}

// validOrderDirections is a map of enum values to their validity
var validOrderDirections = map[OrderDirection]bool{
	OrderDirections.UNKNOWN: false,
	OrderDirections.ASC:     true,
	OrderDirections.DESC:    true,
}

// IsValid checks whether the OrderDirections value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (o OrderDirection) IsValid() bool {
	return validOrderDirections[o]
}

// MarshalJSON implements the json.Marshaler interface for OrderDirection.
// It returns the JSON representation of the enum value as a byte slice.
func (o OrderDirection) MarshalJSON() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for OrderDirection.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (o *OrderDirection) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newo, err := ParseOrderDirection(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for OrderDirection.
// It returns the string representation of the enum value as a byte slice
func (o OrderDirection) MarshalText() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OrderDirection.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *OrderDirection) UnmarshalText(b []byte) error {
	newo, err := ParseOrderDirection(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Scan implements the database/sql.Scanner interface for OrderDirection.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (o *OrderDirection) Scan(value any) error {
	newo, err := ParseOrderDirection(value)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Value implements the database/sql/driver.Valuer interface for OrderDirection.
// It returns the string representation of the enum value.
func (o OrderDirection) Value() (driver.Value, error) {
	return o.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for OrderDirection.
// It returns the binary representation of the enum value as a byte slice.
func (o OrderDirection) MarshalBinary() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for OrderDirection.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *OrderDirection) UnmarshalBinary(b []byte) error {
	newo, err := ParseOrderDirection(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for OrderDirection.
// It returns the string representation of the enum value.
func (o OrderDirection) MarshalYAML() ([]byte, error) {
	return []byte(o.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (o *OrderDirection) UnmarshalYAML(b []byte) error {
	newo, err := ParseOrderDirection(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// orderdirectionNames is a constant string slice containing all enum values cononical absolute names
const orderdirectionNames = "unknownascdesc"

// orderdirectionNamesMap is a map of enum values to their canonical absolute
// name positions within the orderdirectionNames string slice
var orderdirectionNamesMap = map[OrderDirection]string{
	OrderDirections.UNKNOWN: orderdirectionNames[0:7],
	OrderDirections.ASC:     orderdirectionNames[7:10],
	OrderDirections.DESC:    orderdirectionNames[10:14],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (o OrderDirection) String() string {
	if str, ok := orderdirectionNamesMap[o]; ok {
		return str
	}
	return fmt.Sprintf("orderdirection(%d)", o.orderDirection)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[unknown]
	_ = x[asc-1]
	_ = x[desc-2]
}
