// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/log_level/log_level.go

package loglevel

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// LogLevel is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type LogLevel struct {
	logLevel
}

// logLevelsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the LogLevel type.
type logLevelsContainer struct {
	UNKNOWN    LogLevel
	DEBUGLEVEL LogLevel
	INFOLEVEL  LogLevel
	WARNLEVEL  LogLevel
	ERRORLEVEL LogLevel
	PANICLEVEL LogLevel
	FATALLEVEL LogLevel
	TRACELEVEL LogLevel
}

// LogLevels is a main entry point using the LogLevel type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var LogLevels = logLevelsContainer{
	UNKNOWN: LogLevel{
		logLevel: unknown,
	},
	DEBUGLEVEL: LogLevel{
		logLevel: debugLevel,
	},
	INFOLEVEL: LogLevel{
		logLevel: infoLevel,
	},
	WARNLEVEL: LogLevel{
		logLevel: warnLevel,
	},
	ERRORLEVEL: LogLevel{
		logLevel: errorLevel,
	},
	PANICLEVEL: LogLevel{
		logLevel: panicLevel,
	},
	FATALLEVEL: LogLevel{
		logLevel: fatalLevel,
	},
	TRACELEVEL: LogLevel{
		logLevel: traceLevel,
	},
}

// invalidLogLevel is an invalid sentinel value for LogLevel
var invalidLogLevel = LogLevel{
	logLevel: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logLevelsContainer) allSlice() []LogLevel {
	return []LogLevel{
		LogLevels.DEBUGLEVEL,
		LogLevels.INFOLEVEL,
		LogLevels.WARNLEVEL,
		LogLevels.ERRORLEVEL,
		LogLevels.PANICLEVEL,
		LogLevels.FATALLEVEL,
		LogLevels.TRACELEVEL,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logLevelsContainer) All() iter.Seq[LogLevel] {
	return func(yield func(LogLevel) bool) {
		for _, v := range l.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseLogLevel = errors.New("invalid input provided to parse to LogLevel")

// ParseLogLevel parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseLogLevel(input any) (LogLevel, error) {
	switch v := input.(type) {
	case LogLevel:
		return v, nil
	case string:
		if result := stringToLogLevel(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToLogLevel(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToLogLevel(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToLogLevel(v); result != nil {
			return *result, nil
		}
	default:
		return invalidLogLevel, fmt.Errorf("invalid type %T", input)
	}
	return invalidLogLevel, fmt.Errorf("%w: invalid value %v", ErrParseLogLevel, input)
}

// logLevelsNameMap is a map of enum values to their LogLevel representation
// It is used to convert string representations of enum values into their LogLevel representation.
var logLevelsNameMap = map[string]LogLevel{
	"unknown":    LogLevels.UNKNOWN,
	"debugLevel": LogLevels.DEBUGLEVEL,
	"infoLevel":  LogLevels.INFOLEVEL,
	"warnLevel":  LogLevels.WARNLEVEL,
	"errorLevel": LogLevels.ERRORLEVEL,
	"panicLevel": LogLevels.PANICLEVEL,
	"fatalLevel": LogLevels.FATALLEVEL,
	"traceLevel": LogLevels.TRACELEVEL,
}

// stringToLogLevel converts a string representation of an enum value into its LogLevel representation
// It returns a pointer to the LogLevel representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToLogLevel(s string) *LogLevel {
	if t, ok := logLevelsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToLogLevel converts a numeric value to a LogLevel
// It returns a pointer to the LogLevel representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToLogLevel[T number](num T) *LogLevel {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(LogLevels.allSlice()) {
		return nil
	}
	result := LogLevels.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveLogLevels iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveLogLevels(f func(LogLevel)) {
	for _, p := range LogLevels.allSlice() {
		f(p)
	}
}

// validLogLevels is a map of enum values to their validity
var validLogLevels = map[LogLevel]bool{
	LogLevels.UNKNOWN:    false,
	LogLevels.DEBUGLEVEL: true,
	LogLevels.INFOLEVEL:  true,
	LogLevels.WARNLEVEL:  true,
	LogLevels.ERRORLEVEL: true,
	LogLevels.PANICLEVEL: true,
	LogLevels.FATALLEVEL: true,
	LogLevels.TRACELEVEL: true,
}

// IsValid checks whether the LogLevels value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (l LogLevel) IsValid() bool {
	return validLogLevels[l]
}

// MarshalJSON implements the json.Marshaler interface for LogLevel.
// It returns the JSON representation of the enum value as a byte slice.
func (l LogLevel) MarshalJSON() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for LogLevel.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (l *LogLevel) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newl, err := ParseLogLevel(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for LogLevel.
// It returns the string representation of the enum value as a byte slice
func (l LogLevel) MarshalText() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LogLevel.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogLevel) UnmarshalText(b []byte) error {
	newl, err := ParseLogLevel(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Scan implements the database/sql.Scanner interface for LogLevel.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (l *LogLevel) Scan(value any) error {
	newl, err := ParseLogLevel(value)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Value implements the database/sql/driver.Valuer interface for LogLevel.
// It returns the string representation of the enum value.
func (l LogLevel) Value() (driver.Value, error) {
	return l.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for LogLevel.
// It returns the binary representation of the enum value as a byte slice.
func (l LogLevel) MarshalBinary() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for LogLevel.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogLevel) UnmarshalBinary(b []byte) error {
	newl, err := ParseLogLevel(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for LogLevel.
// It returns the string representation of the enum value.
func (l LogLevel) MarshalYAML() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (l *LogLevel) UnmarshalYAML(b []byte) error {
	newl, err := ParseLogLevel(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// loglevelNames is a constant string slice containing all enum values cononical absolute names
const loglevelNames = "unknowndebugLevelinfoLevelwarnLevelerrorLevelpanicLevelfatalLeveltraceLevel"

// loglevelNamesMap is a map of enum values to their canonical absolute
// name positions within the loglevelNames string slice
var loglevelNamesMap = map[LogLevel]string{
	LogLevels.UNKNOWN:    loglevelNames[0:7],
	LogLevels.DEBUGLEVEL: loglevelNames[7:17],
	LogLevels.INFOLEVEL:  loglevelNames[17:26],
	LogLevels.WARNLEVEL:  loglevelNames[26:35],
	LogLevels.ERRORLEVEL: loglevelNames[35:45],
	LogLevels.PANICLEVEL: loglevelNames[45:55],
	LogLevels.FATALLEVEL: loglevelNames[55:65],
	LogLevels.TRACELEVEL: loglevelNames[65:75],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (l LogLevel) String() string {
	if str, ok := loglevelNamesMap[l]; ok {
		return str
	}
	return fmt.Sprintf("loglevel(%d)", l.logLevel)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [8]struct{}
	_ = x[unknown]
	_ = x[debugLevel-1]
	_ = x[infoLevel-2]
	_ = x[warnLevel-3]
	_ = x[errorLevel-4]
	_ = x[panicLevel-5]
	_ = x[fatalLevel-6]
	_ = x[traceLevel-7]
}
