// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:46.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/sql_client_ssl_mode/sql_client_ssl_mode.go

package sqlclientsslmode

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// SqlClientSSLMode is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type SqlClientSSLMode struct {
	sqlClientSSLMode
}

// sqlClientSSLModesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the SqlClientSSLMode type.
type sqlClientSSLModesContainer struct {
	UNKNOWN    SqlClientSSLMode
	DISABLED   SqlClientSSLMode
	REQUIRE    SqlClientSSLMode
	VERIFYCA   SqlClientSSLMode
	VERIFYFULL SqlClientSSLMode
}

// SqlClientSSLModes is a main entry point using the SqlClientSSLMode type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var SqlClientSSLModes = sqlClientSSLModesContainer{
	UNKNOWN: SqlClientSSLMode{
		sqlClientSSLMode: unknown,
	},
	DISABLED: SqlClientSSLMode{
		sqlClientSSLMode: disabled,
	},
	REQUIRE: SqlClientSSLMode{
		sqlClientSSLMode: require,
	},
	VERIFYCA: SqlClientSSLMode{
		sqlClientSSLMode: verifyCA,
	},
	VERIFYFULL: SqlClientSSLMode{
		sqlClientSSLMode: verifyFull,
	},
}

// invalidSqlClientSSLMode is an invalid sentinel value for SqlClientSSLMode
var invalidSqlClientSSLMode = SqlClientSSLMode{
	sqlClientSSLMode: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s sqlClientSSLModesContainer) allSlice() []SqlClientSSLMode {
	return []SqlClientSSLMode{
		SqlClientSSLModes.DISABLED,
		SqlClientSSLModes.REQUIRE,
		SqlClientSSLModes.VERIFYCA,
		SqlClientSSLModes.VERIFYFULL,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s sqlClientSSLModesContainer) All() iter.Seq[SqlClientSSLMode] {
	return func(yield func(SqlClientSSLMode) bool) {
		for _, v := range s.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseSqlClientSSLMode = errors.New("invalid input provided to parse to SqlClientSSLMode")

// ParseSqlClientSSLMode parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseSqlClientSSLMode(input any) (SqlClientSSLMode, error) {
	switch v := input.(type) {
	case SqlClientSSLMode:
		return v, nil
	case string:
		if result := stringToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToSqlClientSSLMode(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToSqlClientSSLMode(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToSqlClientSSLMode(v); result != nil {
			return *result, nil
		}
	default:
		return invalidSqlClientSSLMode, fmt.Errorf("invalid type %T", input)
	}
	return invalidSqlClientSSLMode, fmt.Errorf("%w: invalid value %v", ErrParseSqlClientSSLMode, input)
}

// sqlClientSSLModesNameMap is a map of enum values to their SqlClientSSLMode representation
// It is used to convert string representations of enum values into their SqlClientSSLMode representation.
var sqlClientSSLModesNameMap = map[string]SqlClientSSLMode{
	"unknown":    SqlClientSSLModes.UNKNOWN,
	"disabled":   SqlClientSSLModes.DISABLED,
	"require":    SqlClientSSLModes.REQUIRE,
	"verifyCA":   SqlClientSSLModes.VERIFYCA,
	"verifyFull": SqlClientSSLModes.VERIFYFULL,
}

// stringToSqlClientSSLMode converts a string representation of an enum value into its SqlClientSSLMode representation
// It returns a pointer to the SqlClientSSLMode representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToSqlClientSSLMode(s string) *SqlClientSSLMode {
	if t, ok := sqlClientSSLModesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToSqlClientSSLMode converts a numeric value to a SqlClientSSLMode
// It returns a pointer to the SqlClientSSLMode representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToSqlClientSSLMode[T number](num T) *SqlClientSSLMode {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(SqlClientSSLModes.allSlice()) {
		return nil
	}
	result := SqlClientSSLModes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveSqlClientSSLModes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveSqlClientSSLModes(f func(SqlClientSSLMode)) {
	for _, p := range SqlClientSSLModes.allSlice() {
		f(p)
	}
}

// validSqlClientSSLModes is a map of enum values to their validity
var validSqlClientSSLModes = map[SqlClientSSLMode]bool{
	SqlClientSSLModes.UNKNOWN:    false,
	SqlClientSSLModes.DISABLED:   true,
	SqlClientSSLModes.REQUIRE:    true,
	SqlClientSSLModes.VERIFYCA:   true,
	SqlClientSSLModes.VERIFYFULL: true,
}

// IsValid checks whether the SqlClientSSLModes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (s SqlClientSSLMode) IsValid() bool {
	return validSqlClientSSLModes[s]
}

// MarshalJSON implements the json.Marshaler interface for SqlClientSSLMode.
// It returns the JSON representation of the enum value as a byte slice.
func (s SqlClientSSLMode) MarshalJSON() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SqlClientSSLMode.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (s *SqlClientSSLMode) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	news, err := ParseSqlClientSSLMode(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for SqlClientSSLMode.
// It returns the string representation of the enum value as a byte slice
func (s SqlClientSSLMode) MarshalText() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SqlClientSSLMode.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SqlClientSSLMode) UnmarshalText(b []byte) error {
	news, err := ParseSqlClientSSLMode(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Scan implements the database/sql.Scanner interface for SqlClientSSLMode.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (s *SqlClientSSLMode) Scan(value any) error {
	news, err := ParseSqlClientSSLMode(value)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Value implements the database/sql/driver.Valuer interface for SqlClientSSLMode.
// It returns the string representation of the enum value.
func (s SqlClientSSLMode) Value() (driver.Value, error) {
	return s.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for SqlClientSSLMode.
// It returns the binary representation of the enum value as a byte slice.
func (s SqlClientSSLMode) MarshalBinary() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for SqlClientSSLMode.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SqlClientSSLMode) UnmarshalBinary(b []byte) error {
	news, err := ParseSqlClientSSLMode(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for SqlClientSSLMode.
// It returns the string representation of the enum value.
func (s SqlClientSSLMode) MarshalYAML() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (s *SqlClientSSLMode) UnmarshalYAML(b []byte) error {
	news, err := ParseSqlClientSSLMode(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// sqlclientsslmodeNames is a constant string slice containing all enum values cononical absolute names
const sqlclientsslmodeNames = "unknowndisabledrequireverifyCAverifyFull"

// sqlclientsslmodeNamesMap is a map of enum values to their canonical absolute
// name positions within the sqlclientsslmodeNames string slice
var sqlclientsslmodeNamesMap = map[SqlClientSSLMode]string{
	SqlClientSSLModes.UNKNOWN:    sqlclientsslmodeNames[0:7],
	SqlClientSSLModes.DISABLED:   sqlclientsslmodeNames[7:15],
	SqlClientSSLModes.REQUIRE:    sqlclientsslmodeNames[15:22],
	SqlClientSSLModes.VERIFYCA:   sqlclientsslmodeNames[22:30],
	SqlClientSSLModes.VERIFYFULL: sqlclientsslmodeNames[30:40],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (s SqlClientSSLMode) String() string {
	if str, ok := sqlclientsslmodeNamesMap[s]; ok {
		return str
	}
	return fmt.Sprintf("sqlclientsslmode(%d)", s.sqlClientSSLMode)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[unknown]
	_ = x[disabled-1]
	_ = x[require-2]
	_ = x[verifyCA-3]
	_ = x[verifyFull-4]
}
