// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/rpc/rpc_server/contracts/rpc_server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	contracts "frisboo-bank/openapi-generator-service/pkg/logger/contracts"
	rpcservertype "frisboo-bank/openapi-generator-service/pkg/rpc/rpc_server/models/enums/rpc_server_type"
	registrar "frisboo-bank/openapi-generator-service/pkg/rpc/rpc_server/registrar"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRPCServer is a mock of RPCServer interface.
type MockRPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockRPCServerMockRecorder
}

// MockRPCServerMockRecorder is the mock recorder for MockRPCServer.
type MockRPCServerMockRecorder struct {
	mock *MockRPCServer
}

// NewMockRPCServer creates a new mock instance.
func NewMockRPCServer(ctrl *gomock.Controller) *MockRPCServer {
	mock := &MockRPCServer{ctrl: ctrl}
	mock.recorder = &MockRPCServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCServer) EXPECT() *MockRPCServerMockRecorder {
	return m.recorder
}

// AddMiddlewares mocks base method.
func (m *MockRPCServer) AddMiddlewares(middlewares ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddMiddlewares", varargs...)
}

// AddMiddlewares indicates an expected call of AddMiddlewares.
func (mr *MockRPCServerMockRecorder) AddMiddlewares(middlewares ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddlewares", reflect.TypeOf((*MockRPCServer)(nil).AddMiddlewares), middlewares...)
}

// ListServices mocks base method.
func (m *MockRPCServer) ListServices() []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices")
	ret0, _ := ret[0].([]any)
	return ret0
}

// ListServices indicates an expected call of ListServices.
func (mr *MockRPCServerMockRecorder) ListServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockRPCServer)(nil).ListServices))
}

// Logger mocks base method.
func (m *MockRPCServer) Logger() contracts.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockRPCServerMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockRPCServer)(nil).Logger))
}

// Name mocks base method.
func (m *MockRPCServer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRPCServerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRPCServer)(nil).Name))
}

// ServiceManager mocks base method.
func (m *MockRPCServer) ServiceManager() *registrar.ServiceManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceManager")
	ret0, _ := ret[0].(*registrar.ServiceManager)
	return ret0
}

// ServiceManager indicates an expected call of ServiceManager.
func (mr *MockRPCServerMockRecorder) ServiceManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceManager", reflect.TypeOf((*MockRPCServer)(nil).ServiceManager))
}

// SetupDefaultMiddlewares mocks base method.
func (m *MockRPCServer) SetupDefaultMiddlewares() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupDefaultMiddlewares")
}

// SetupDefaultMiddlewares indicates an expected call of SetupDefaultMiddlewares.
func (mr *MockRPCServerMockRecorder) SetupDefaultMiddlewares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDefaultMiddlewares", reflect.TypeOf((*MockRPCServer)(nil).SetupDefaultMiddlewares))
}

// Start mocks base method.
func (m *MockRPCServer) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRPCServerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRPCServer)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRPCServer) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRPCServerMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRPCServer)(nil).Stop), ctx)
}

// Type mocks base method.
func (m *MockRPCServer) Type() rpcservertype.RpcServerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(rpcservertype.RpcServerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRPCServerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRPCServer)(nil).Type))
}

// MockRPCServerAdapter is a mock of RPCServerAdapter interface.
type MockRPCServerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRPCServerAdapterMockRecorder
}

// MockRPCServerAdapterMockRecorder is the mock recorder for MockRPCServerAdapter.
type MockRPCServerAdapterMockRecorder struct {
	mock *MockRPCServerAdapter
}

// NewMockRPCServerAdapter creates a new mock instance.
func NewMockRPCServerAdapter(ctrl *gomock.Controller) *MockRPCServerAdapter {
	mock := &MockRPCServerAdapter{ctrl: ctrl}
	mock.recorder = &MockRPCServerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCServerAdapter) EXPECT() *MockRPCServerAdapterMockRecorder {
	return m.recorder
}

// AddMiddlewares mocks base method.
func (m *MockRPCServerAdapter) AddMiddlewares(middlewares ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddMiddlewares", varargs...)
}

// AddMiddlewares indicates an expected call of AddMiddlewares.
func (mr *MockRPCServerAdapterMockRecorder) AddMiddlewares(middlewares ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddlewares", reflect.TypeOf((*MockRPCServerAdapter)(nil).AddMiddlewares), middlewares...)
}

// ListServices mocks base method.
func (m *MockRPCServerAdapter) ListServices() []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices")
	ret0, _ := ret[0].([]any)
	return ret0
}

// ListServices indicates an expected call of ListServices.
func (mr *MockRPCServerAdapterMockRecorder) ListServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockRPCServerAdapter)(nil).ListServices))
}

// Logger mocks base method.
func (m *MockRPCServerAdapter) Logger() contracts.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockRPCServerAdapterMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockRPCServerAdapter)(nil).Logger))
}

// Name mocks base method.
func (m *MockRPCServerAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRPCServerAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRPCServerAdapter)(nil).Name))
}

// ServiceManager mocks base method.
func (m *MockRPCServerAdapter) ServiceManager() *registrar.ServiceManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceManager")
	ret0, _ := ret[0].(*registrar.ServiceManager)
	return ret0
}

// ServiceManager indicates an expected call of ServiceManager.
func (mr *MockRPCServerAdapterMockRecorder) ServiceManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceManager", reflect.TypeOf((*MockRPCServerAdapter)(nil).ServiceManager))
}

// SetupDefaultMiddlewares mocks base method.
func (m *MockRPCServerAdapter) SetupDefaultMiddlewares() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupDefaultMiddlewares")
}

// SetupDefaultMiddlewares indicates an expected call of SetupDefaultMiddlewares.
func (mr *MockRPCServerAdapterMockRecorder) SetupDefaultMiddlewares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDefaultMiddlewares", reflect.TypeOf((*MockRPCServerAdapter)(nil).SetupDefaultMiddlewares))
}

// Start mocks base method.
func (m *MockRPCServerAdapter) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRPCServerAdapterMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRPCServerAdapter)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRPCServerAdapter) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRPCServerAdapterMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRPCServerAdapter)(nil).Stop), ctx)
}

// Type mocks base method.
func (m *MockRPCServerAdapter) Type() rpcservertype.RpcServerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(rpcservertype.RpcServerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRPCServerAdapterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRPCServerAdapter)(nil).Type))
}
