// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/rpc_server_type/rpc_server_type.go

package rpcservertype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// RpcServerType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type RpcServerType struct {
	rpcServerType
}

// rpcServerTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the RpcServerType type.
type rpcServerTypesContainer struct {
	UNKNOWN RpcServerType
	GRPC    RpcServerType
}

// RpcServerTypes is a main entry point using the RpcServerType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var RpcServerTypes = rpcServerTypesContainer{
	UNKNOWN: RpcServerType{
		rpcServerType: unknown,
	},
	GRPC: RpcServerType{
		rpcServerType: grpc,
	},
}

// invalidRpcServerType is an invalid sentinel value for RpcServerType
var invalidRpcServerType = RpcServerType{
	rpcServerType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r rpcServerTypesContainer) allSlice() []RpcServerType {
	return []RpcServerType{
		RpcServerTypes.GRPC,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r rpcServerTypesContainer) All() iter.Seq[RpcServerType] {
	return func(yield func(RpcServerType) bool) {
		for _, v := range r.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseRpcServerType = errors.New("invalid input provided to parse to RpcServerType")

// ParseRpcServerType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseRpcServerType(input any) (RpcServerType, error) {
	switch v := input.(type) {
	case RpcServerType:
		return v, nil
	case string:
		if result := stringToRpcServerType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToRpcServerType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToRpcServerType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToRpcServerType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidRpcServerType, fmt.Errorf("invalid type %T", input)
	}
	return invalidRpcServerType, fmt.Errorf("%w: invalid value %v", ErrParseRpcServerType, input)
}

// rpcServerTypesNameMap is a map of enum values to their RpcServerType representation
// It is used to convert string representations of enum values into their RpcServerType representation.
var rpcServerTypesNameMap = map[string]RpcServerType{
	"unknown": RpcServerTypes.UNKNOWN,
	"grpc":    RpcServerTypes.GRPC,
}

// stringToRpcServerType converts a string representation of an enum value into its RpcServerType representation
// It returns a pointer to the RpcServerType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToRpcServerType(s string) *RpcServerType {
	if t, ok := rpcServerTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToRpcServerType converts a numeric value to a RpcServerType
// It returns a pointer to the RpcServerType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToRpcServerType[T number](num T) *RpcServerType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(RpcServerTypes.allSlice()) {
		return nil
	}
	result := RpcServerTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveRpcServerTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveRpcServerTypes(f func(RpcServerType)) {
	for _, p := range RpcServerTypes.allSlice() {
		f(p)
	}
}

// validRpcServerTypes is a map of enum values to their validity
var validRpcServerTypes = map[RpcServerType]bool{
	RpcServerTypes.UNKNOWN: false,
	RpcServerTypes.GRPC:    true,
}

// IsValid checks whether the RpcServerTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (r RpcServerType) IsValid() bool {
	return validRpcServerTypes[r]
}

// MarshalJSON implements the json.Marshaler interface for RpcServerType.
// It returns the JSON representation of the enum value as a byte slice.
func (r RpcServerType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for RpcServerType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (r *RpcServerType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newr, err := ParseRpcServerType(b)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for RpcServerType.
// It returns the string representation of the enum value as a byte slice
func (r RpcServerType) MarshalText() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for RpcServerType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *RpcServerType) UnmarshalText(b []byte) error {
	newr, err := ParseRpcServerType(b)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Scan implements the database/sql.Scanner interface for RpcServerType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (r *RpcServerType) Scan(value any) error {
	newr, err := ParseRpcServerType(value)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Value implements the database/sql/driver.Valuer interface for RpcServerType.
// It returns the string representation of the enum value.
func (r RpcServerType) Value() (driver.Value, error) {
	return r.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for RpcServerType.
// It returns the binary representation of the enum value as a byte slice.
func (r RpcServerType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for RpcServerType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *RpcServerType) UnmarshalBinary(b []byte) error {
	newr, err := ParseRpcServerType(b)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for RpcServerType.
// It returns the string representation of the enum value.
func (r RpcServerType) MarshalYAML() ([]byte, error) {
	return []byte(r.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (r *RpcServerType) UnmarshalYAML(b []byte) error {
	newr, err := ParseRpcServerType(b)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// rpcservertypeNames is a constant string slice containing all enum values cononical absolute names
const rpcservertypeNames = "unknowngrpc"

// rpcservertypeNamesMap is a map of enum values to their canonical absolute
// name positions within the rpcservertypeNames string slice
var rpcservertypeNamesMap = map[RpcServerType]string{
	RpcServerTypes.UNKNOWN: rpcservertypeNames[0:7],
	RpcServerTypes.GRPC:    rpcservertypeNames[7:11],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (r RpcServerType) String() string {
	if str, ok := rpcservertypeNamesMap[r]; ok {
		return str
	}
	return fmt.Sprintf("rpcservertype(%d)", r.rpcServerType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[unknown]
	_ = x[grpc-1]
}
