// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/logical_operator/logical_operator.go

package logicaloperator

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// LogicalOperator is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type LogicalOperator struct {
	logicalOperator
}

// logicalOperatorsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the LogicalOperator type.
type logicalOperatorsContainer struct {
	UNKNOWN LogicalOperator
	AND     LogicalOperator
	OR      LogicalOperator
}

// LogicalOperators is a main entry point using the LogicalOperator type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var LogicalOperators = logicalOperatorsContainer{
	UNKNOWN: LogicalOperator{
		logicalOperator: unknown,
	},
	AND: LogicalOperator{
		logicalOperator: and,
	},
	OR: LogicalOperator{
		logicalOperator: or,
	},
}

// invalidLogicalOperator is an invalid sentinel value for LogicalOperator
var invalidLogicalOperator = LogicalOperator{
	logicalOperator: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logicalOperatorsContainer) allSlice() []LogicalOperator {
	return []LogicalOperator{
		LogicalOperators.AND,
		LogicalOperators.OR,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logicalOperatorsContainer) All() iter.Seq[LogicalOperator] {
	return func(yield func(LogicalOperator) bool) {
		for _, v := range l.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseLogicalOperator = errors.New("invalid input provided to parse to LogicalOperator")

// ParseLogicalOperator parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseLogicalOperator(input any) (LogicalOperator, error) {
	switch v := input.(type) {
	case LogicalOperator:
		return v, nil
	case string:
		if result := stringToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToLogicalOperator(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToLogicalOperator(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToLogicalOperator(v); result != nil {
			return *result, nil
		}
	default:
		return invalidLogicalOperator, fmt.Errorf("invalid type %T", input)
	}
	return invalidLogicalOperator, fmt.Errorf("%w: invalid value %v", ErrParseLogicalOperator, input)
}

// logicalOperatorsNameMap is a map of enum values to their LogicalOperator representation
// It is used to convert string representations of enum values into their LogicalOperator representation.
var logicalOperatorsNameMap = map[string]LogicalOperator{
	"unknown": LogicalOperators.UNKNOWN,
	"and":     LogicalOperators.AND,
	"or":      LogicalOperators.OR,
}

// stringToLogicalOperator converts a string representation of an enum value into its LogicalOperator representation
// It returns a pointer to the LogicalOperator representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToLogicalOperator(s string) *LogicalOperator {
	if t, ok := logicalOperatorsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToLogicalOperator converts a numeric value to a LogicalOperator
// It returns a pointer to the LogicalOperator representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToLogicalOperator[T number](num T) *LogicalOperator {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(LogicalOperators.allSlice()) {
		return nil
	}
	result := LogicalOperators.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveLogicalOperators iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveLogicalOperators(f func(LogicalOperator)) {
	for _, p := range LogicalOperators.allSlice() {
		f(p)
	}
}

// validLogicalOperators is a map of enum values to their validity
var validLogicalOperators = map[LogicalOperator]bool{
	LogicalOperators.UNKNOWN: false,
	LogicalOperators.AND:     true,
	LogicalOperators.OR:      true,
}

// IsValid checks whether the LogicalOperators value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (l LogicalOperator) IsValid() bool {
	return validLogicalOperators[l]
}

// MarshalJSON implements the json.Marshaler interface for LogicalOperator.
// It returns the JSON representation of the enum value as a byte slice.
func (l LogicalOperator) MarshalJSON() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for LogicalOperator.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (l *LogicalOperator) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newl, err := ParseLogicalOperator(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for LogicalOperator.
// It returns the string representation of the enum value as a byte slice
func (l LogicalOperator) MarshalText() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LogicalOperator.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogicalOperator) UnmarshalText(b []byte) error {
	newl, err := ParseLogicalOperator(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Scan implements the database/sql.Scanner interface for LogicalOperator.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (l *LogicalOperator) Scan(value any) error {
	newl, err := ParseLogicalOperator(value)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Value implements the database/sql/driver.Valuer interface for LogicalOperator.
// It returns the string representation of the enum value.
func (l LogicalOperator) Value() (driver.Value, error) {
	return l.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for LogicalOperator.
// It returns the binary representation of the enum value as a byte slice.
func (l LogicalOperator) MarshalBinary() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for LogicalOperator.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogicalOperator) UnmarshalBinary(b []byte) error {
	newl, err := ParseLogicalOperator(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for LogicalOperator.
// It returns the string representation of the enum value.
func (l LogicalOperator) MarshalYAML() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (l *LogicalOperator) UnmarshalYAML(b []byte) error {
	newl, err := ParseLogicalOperator(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// logicaloperatorNames is a constant string slice containing all enum values cononical absolute names
const logicaloperatorNames = "unknownandor"

// logicaloperatorNamesMap is a map of enum values to their canonical absolute
// name positions within the logicaloperatorNames string slice
var logicaloperatorNamesMap = map[LogicalOperator]string{
	LogicalOperators.UNKNOWN: logicaloperatorNames[0:7],
	LogicalOperators.AND:     logicaloperatorNames[7:10],
	LogicalOperators.OR:      logicaloperatorNames[10:12],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (l LogicalOperator) String() string {
	if str, ok := logicaloperatorNamesMap[l]; ok {
		return str
	}
	return fmt.Sprintf("logicaloperator(%d)", l.logicalOperator)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[unknown]
	_ = x[and-1]
	_ = x[or-2]
}
