// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/logger/contracts/logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	contracts "frisboo-bank/openapi-generator-service/pkg/logger/contracts"
	loggertype "frisboo-bank/openapi-generator-service/pkg/logger/models/enums/logger_type"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), args...)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Debugw mocks base method.
func (m *MockLogger) Debugw(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debugw", msg, fields)
}

// Debugw indicates an expected call of Debugw.
func (mr *MockLoggerMockRecorder) Debugw(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugw", reflect.TypeOf((*MockLogger)(nil).Debugw), msg, fields)
}

// Err mocks base method.
func (m *MockLogger) Err(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Err", msg, err)
}

// Err indicates an expected call of Err.
func (mr *MockLoggerMockRecorder) Err(msg, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockLogger)(nil).Err), msg, err)
}

// Error mocks base method.
func (m *MockLogger) Error(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), args...)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Errorw mocks base method.
func (m *MockLogger) Errorw(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Errorw", msg, fields)
}

// Errorw indicates an expected call of Errorw.
func (mr *MockLoggerMockRecorder) Errorw(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorw", reflect.TypeOf((*MockLogger)(nil).Errorw), msg, fields)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), args...)
}

// Fatalf mocks base method.
func (m *MockLogger) Fatalf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerMockRecorder) Fatalf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// GrpcClientInterceptorLogger mocks base method.
func (m *MockLogger) GrpcClientInterceptorLogger(method string, req, reply any, time time.Duration, metaData map[string][]string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrpcClientInterceptorLogger", method, req, reply, time, metaData, err)
}

// GrpcClientInterceptorLogger indicates an expected call of GrpcClientInterceptorLogger.
func (mr *MockLoggerMockRecorder) GrpcClientInterceptorLogger(method, req, reply, time, metaData, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrpcClientInterceptorLogger", reflect.TypeOf((*MockLogger)(nil).GrpcClientInterceptorLogger), method, req, reply, time, metaData, err)
}

// GrpcMiddlewareAccessLogger mocks base method.
func (m *MockLogger) GrpcMiddlewareAccessLogger(method string, time time.Duration, metaData map[string][]string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrpcMiddlewareAccessLogger", method, time, metaData, err)
}

// GrpcMiddlewareAccessLogger indicates an expected call of GrpcMiddlewareAccessLogger.
func (mr *MockLoggerMockRecorder) GrpcMiddlewareAccessLogger(method, time, metaData, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrpcMiddlewareAccessLogger", reflect.TypeOf((*MockLogger)(nil).GrpcMiddlewareAccessLogger), method, time, metaData, err)
}

// Info mocks base method.
func (m *MockLogger) Info(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), args...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Infow mocks base method.
func (m *MockLogger) Infow(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Infow", msg, fields)
}

// Infow indicates an expected call of Infow.
func (mr *MockLoggerMockRecorder) Infow(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infow", reflect.TypeOf((*MockLogger)(nil).Infow), msg, fields)
}

// Name mocks base method.
func (m *MockLogger) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockLoggerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockLogger)(nil).Name))
}

// Printf mocks base method.
func (m *MockLogger) Printf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Printf", varargs...)
}

// Printf indicates an expected call of Printf.
func (mr *MockLoggerMockRecorder) Printf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Printf", reflect.TypeOf((*MockLogger)(nil).Printf), varargs...)
}

// Type mocks base method.
func (m *MockLogger) Type() loggertype.LoggerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(loggertype.LoggerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockLoggerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockLogger)(nil).Type))
}

// Warn mocks base method.
func (m *MockLogger) Warn(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), args...)
}

// WarnMsg mocks base method.
func (m *MockLogger) WarnMsg(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WarnMsg", msg, err)
}

// WarnMsg indicates an expected call of WarnMsg.
func (mr *MockLoggerMockRecorder) WarnMsg(msg, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnMsg", reflect.TypeOf((*MockLogger)(nil).WarnMsg), msg, err)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// WithName mocks base method.
func (m *MockLogger) WithName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithName", name)
}

// WithName indicates an expected call of WithName.
func (mr *MockLoggerMockRecorder) WithName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithName", reflect.TypeOf((*MockLogger)(nil).WithName), name)
}

// MockLoggerAdapter is a mock of LoggerAdapter interface.
type MockLoggerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerAdapterMockRecorder
}

// MockLoggerAdapterMockRecorder is the mock recorder for MockLoggerAdapter.
type MockLoggerAdapterMockRecorder struct {
	mock *MockLoggerAdapter
}

// NewMockLoggerAdapter creates a new mock instance.
func NewMockLoggerAdapter(ctrl *gomock.Controller) *MockLoggerAdapter {
	mock := &MockLoggerAdapter{ctrl: ctrl}
	mock.recorder = &MockLoggerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerAdapter) EXPECT() *MockLoggerAdapterMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLoggerAdapter) Debug(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerAdapterMockRecorder) Debug(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLoggerAdapter)(nil).Debug), args...)
}

// Debugf mocks base method.
func (m *MockLoggerAdapter) Debugf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerAdapterMockRecorder) Debugf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLoggerAdapter)(nil).Debugf), varargs...)
}

// Debugw mocks base method.
func (m *MockLoggerAdapter) Debugw(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debugw", msg, fields)
}

// Debugw indicates an expected call of Debugw.
func (mr *MockLoggerAdapterMockRecorder) Debugw(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugw", reflect.TypeOf((*MockLoggerAdapter)(nil).Debugw), msg, fields)
}

// Err mocks base method.
func (m *MockLoggerAdapter) Err(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Err", msg, err)
}

// Err indicates an expected call of Err.
func (mr *MockLoggerAdapterMockRecorder) Err(msg, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockLoggerAdapter)(nil).Err), msg, err)
}

// Error mocks base method.
func (m *MockLoggerAdapter) Error(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerAdapterMockRecorder) Error(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLoggerAdapter)(nil).Error), args...)
}

// Errorf mocks base method.
func (m *MockLoggerAdapter) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerAdapterMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLoggerAdapter)(nil).Errorf), varargs...)
}

// Errorw mocks base method.
func (m *MockLoggerAdapter) Errorw(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Errorw", msg, fields)
}

// Errorw indicates an expected call of Errorw.
func (mr *MockLoggerAdapterMockRecorder) Errorw(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorw", reflect.TypeOf((*MockLoggerAdapter)(nil).Errorw), msg, fields)
}

// Fatal mocks base method.
func (m *MockLoggerAdapter) Fatal(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerAdapterMockRecorder) Fatal(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLoggerAdapter)(nil).Fatal), args...)
}

// Fatalf mocks base method.
func (m *MockLoggerAdapter) Fatalf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerAdapterMockRecorder) Fatalf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLoggerAdapter)(nil).Fatalf), varargs...)
}

// GrpcClientInterceptorLogger mocks base method.
func (m *MockLoggerAdapter) GrpcClientInterceptorLogger(method string, req, reply any, time time.Duration, metaData map[string][]string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrpcClientInterceptorLogger", method, req, reply, time, metaData, err)
}

// GrpcClientInterceptorLogger indicates an expected call of GrpcClientInterceptorLogger.
func (mr *MockLoggerAdapterMockRecorder) GrpcClientInterceptorLogger(method, req, reply, time, metaData, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrpcClientInterceptorLogger", reflect.TypeOf((*MockLoggerAdapter)(nil).GrpcClientInterceptorLogger), method, req, reply, time, metaData, err)
}

// GrpcMiddlewareAccessLogger mocks base method.
func (m *MockLoggerAdapter) GrpcMiddlewareAccessLogger(method string, time time.Duration, metaData map[string][]string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrpcMiddlewareAccessLogger", method, time, metaData, err)
}

// GrpcMiddlewareAccessLogger indicates an expected call of GrpcMiddlewareAccessLogger.
func (mr *MockLoggerAdapterMockRecorder) GrpcMiddlewareAccessLogger(method, time, metaData, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrpcMiddlewareAccessLogger", reflect.TypeOf((*MockLoggerAdapter)(nil).GrpcMiddlewareAccessLogger), method, time, metaData, err)
}

// Info mocks base method.
func (m *MockLoggerAdapter) Info(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerAdapterMockRecorder) Info(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLoggerAdapter)(nil).Info), args...)
}

// Infof mocks base method.
func (m *MockLoggerAdapter) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerAdapterMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLoggerAdapter)(nil).Infof), varargs...)
}

// Infow mocks base method.
func (m *MockLoggerAdapter) Infow(msg string, fields contracts.Fields) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Infow", msg, fields)
}

// Infow indicates an expected call of Infow.
func (mr *MockLoggerAdapterMockRecorder) Infow(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infow", reflect.TypeOf((*MockLoggerAdapter)(nil).Infow), msg, fields)
}

// Name mocks base method.
func (m *MockLoggerAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockLoggerAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockLoggerAdapter)(nil).Name))
}

// Printf mocks base method.
func (m *MockLoggerAdapter) Printf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Printf", varargs...)
}

// Printf indicates an expected call of Printf.
func (mr *MockLoggerAdapterMockRecorder) Printf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Printf", reflect.TypeOf((*MockLoggerAdapter)(nil).Printf), varargs...)
}

// Type mocks base method.
func (m *MockLoggerAdapter) Type() loggertype.LoggerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(loggertype.LoggerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockLoggerAdapterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockLoggerAdapter)(nil).Type))
}

// Warn mocks base method.
func (m *MockLoggerAdapter) Warn(args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerAdapterMockRecorder) Warn(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLoggerAdapter)(nil).Warn), args...)
}

// WarnMsg mocks base method.
func (m *MockLoggerAdapter) WarnMsg(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WarnMsg", msg, err)
}

// WarnMsg indicates an expected call of WarnMsg.
func (mr *MockLoggerAdapterMockRecorder) WarnMsg(msg, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnMsg", reflect.TypeOf((*MockLoggerAdapter)(nil).WarnMsg), msg, err)
}

// Warnf mocks base method.
func (m *MockLoggerAdapter) Warnf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerAdapterMockRecorder) Warnf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLoggerAdapter)(nil).Warnf), varargs...)
}

// WithName mocks base method.
func (m *MockLoggerAdapter) WithName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithName", name)
}

// WithName indicates an expected call of WithName.
func (mr *MockLoggerAdapterMockRecorder) WithName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithName", reflect.TypeOf((*MockLoggerAdapter)(nil).WithName), name)
}
