// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/logger_type/logger_type.go

package loggertype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// LoggerType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type LoggerType struct {
	loggerType
}

// loggerTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the LoggerType type.
type loggerTypesContainer struct {
	UNKNOWN LoggerType
	LOGRUS  LoggerType
	NOOP    LoggerType
	ZEROLOG LoggerType
}

// LoggerTypes is a main entry point using the LoggerType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var LoggerTypes = loggerTypesContainer{
	UNKNOWN: LoggerType{
		loggerType: unknown,
	},
	LOGRUS: LoggerType{
		loggerType: logrus,
	},
	NOOP: LoggerType{
		loggerType: noop,
	},
	ZEROLOG: LoggerType{
		loggerType: zerolog,
	},
}

// invalidLoggerType is an invalid sentinel value for LoggerType
var invalidLoggerType = LoggerType{
	loggerType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l loggerTypesContainer) allSlice() []LoggerType {
	return []LoggerType{
		LoggerTypes.UNKNOWN,
		LoggerTypes.LOGRUS,
		LoggerTypes.NOOP,
		LoggerTypes.ZEROLOG,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l loggerTypesContainer) All() iter.Seq[LoggerType] {
	return func(yield func(LoggerType) bool) {
		for _, v := range l.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseLoggerType = errors.New("invalid input provided to parse to LoggerType")

// ParseLoggerType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseLoggerType(input any) (LoggerType, error) {
	switch v := input.(type) {
	case LoggerType:
		return v, nil
	case string:
		if result := stringToLoggerType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToLoggerType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToLoggerType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToLoggerType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidLoggerType, fmt.Errorf("invalid type %T", input)
	}
	return invalidLoggerType, fmt.Errorf("%w: invalid value %v", ErrParseLoggerType, input)
}

// loggerTypesNameMap is a map of enum values to their LoggerType representation
// It is used to convert string representations of enum values into their LoggerType representation.
var loggerTypesNameMap = map[string]LoggerType{
	"unknown": LoggerTypes.UNKNOWN,
	"logrus":  LoggerTypes.LOGRUS,
	"noop":    LoggerTypes.NOOP,
	"zerolog": LoggerTypes.ZEROLOG,
}

// stringToLoggerType converts a string representation of an enum value into its LoggerType representation
// It returns a pointer to the LoggerType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToLoggerType(s string) *LoggerType {
	if t, ok := loggerTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToLoggerType converts a numeric value to a LoggerType
// It returns a pointer to the LoggerType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToLoggerType[T number](num T) *LoggerType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(LoggerTypes.allSlice()) {
		return nil
	}
	result := LoggerTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveLoggerTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveLoggerTypes(f func(LoggerType)) {
	for _, p := range LoggerTypes.allSlice() {
		f(p)
	}
}

// validLoggerTypes is a map of enum values to their validity
var validLoggerTypes = map[LoggerType]bool{
	LoggerTypes.UNKNOWN: true,
	LoggerTypes.LOGRUS:  true,
	LoggerTypes.NOOP:    true,
	LoggerTypes.ZEROLOG: true,
}

// IsValid checks whether the LoggerTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (l LoggerType) IsValid() bool {
	return validLoggerTypes[l]
}

// MarshalJSON implements the json.Marshaler interface for LoggerType.
// It returns the JSON representation of the enum value as a byte slice.
func (l LoggerType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for LoggerType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (l *LoggerType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newl, err := ParseLoggerType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for LoggerType.
// It returns the string representation of the enum value as a byte slice
func (l LoggerType) MarshalText() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LoggerType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LoggerType) UnmarshalText(b []byte) error {
	newl, err := ParseLoggerType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Scan implements the database/sql.Scanner interface for LoggerType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (l *LoggerType) Scan(value any) error {
	newl, err := ParseLoggerType(value)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Value implements the database/sql/driver.Valuer interface for LoggerType.
// It returns the string representation of the enum value.
func (l LoggerType) Value() (driver.Value, error) {
	return l.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for LoggerType.
// It returns the binary representation of the enum value as a byte slice.
func (l LoggerType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for LoggerType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LoggerType) UnmarshalBinary(b []byte) error {
	newl, err := ParseLoggerType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for LoggerType.
// It returns the string representation of the enum value.
func (l LoggerType) MarshalYAML() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (l *LoggerType) UnmarshalYAML(b []byte) error {
	newl, err := ParseLoggerType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// loggertypeNames is a constant string slice containing all enum values cononical absolute names
const loggertypeNames = "unknownlogrusnoopzerolog"

// loggertypeNamesMap is a map of enum values to their canonical absolute
// name positions within the loggertypeNames string slice
var loggertypeNamesMap = map[LoggerType]string{
	LoggerTypes.UNKNOWN: loggertypeNames[0:7],
	LoggerTypes.LOGRUS:  loggertypeNames[7:13],
	LoggerTypes.NOOP:    loggertypeNames[13:17],
	LoggerTypes.ZEROLOG: loggertypeNames[17:24],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (l LoggerType) String() string {
	if str, ok := loggertypeNamesMap[l]; ok {
		return str
	}
	return fmt.Sprintf("loggertype(%d)", l.loggerType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[unknown]
	_ = x[logrus-1]
	_ = x[noop-2]
	_ = x[zerolog-3]
}
