// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:46.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/migration_type/migration_type.go

package migrationtype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// MigrationType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type MigrationType struct {
	migrationType
}

// migrationTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the MigrationType type.
type migrationTypesContainer struct {
	UNKNOWN MigrationType
	GOOSE   MigrationType
}

// MigrationTypes is a main entry point using the MigrationType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var MigrationTypes = migrationTypesContainer{
	UNKNOWN: MigrationType{
		migrationType: unknown,
	},
	GOOSE: MigrationType{
		migrationType: goose,
	},
}

// invalidMigrationType is an invalid sentinel value for MigrationType
var invalidMigrationType = MigrationType{
	migrationType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (m migrationTypesContainer) allSlice() []MigrationType {
	return []MigrationType{
		MigrationTypes.GOOSE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (m migrationTypesContainer) All() iter.Seq[MigrationType] {
	return func(yield func(MigrationType) bool) {
		for _, v := range m.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseMigrationType = errors.New("invalid input provided to parse to MigrationType")

// ParseMigrationType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseMigrationType(input any) (MigrationType, error) {
	switch v := input.(type) {
	case MigrationType:
		return v, nil
	case string:
		if result := stringToMigrationType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToMigrationType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToMigrationType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToMigrationType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidMigrationType, fmt.Errorf("invalid type %T", input)
	}
	return invalidMigrationType, fmt.Errorf("%w: invalid value %v", ErrParseMigrationType, input)
}

// migrationTypesNameMap is a map of enum values to their MigrationType representation
// It is used to convert string representations of enum values into their MigrationType representation.
var migrationTypesNameMap = map[string]MigrationType{
	"unknown": MigrationTypes.UNKNOWN,
	"goose":   MigrationTypes.GOOSE,
}

// stringToMigrationType converts a string representation of an enum value into its MigrationType representation
// It returns a pointer to the MigrationType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToMigrationType(s string) *MigrationType {
	if t, ok := migrationTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToMigrationType converts a numeric value to a MigrationType
// It returns a pointer to the MigrationType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToMigrationType[T number](num T) *MigrationType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(MigrationTypes.allSlice()) {
		return nil
	}
	result := MigrationTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveMigrationTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveMigrationTypes(f func(MigrationType)) {
	for _, p := range MigrationTypes.allSlice() {
		f(p)
	}
}

// validMigrationTypes is a map of enum values to their validity
var validMigrationTypes = map[MigrationType]bool{
	MigrationTypes.UNKNOWN: false,
	MigrationTypes.GOOSE:   true,
}

// IsValid checks whether the MigrationTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (m MigrationType) IsValid() bool {
	return validMigrationTypes[m]
}

// MarshalJSON implements the json.Marshaler interface for MigrationType.
// It returns the JSON representation of the enum value as a byte slice.
func (m MigrationType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + m.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for MigrationType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (m *MigrationType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newm, err := ParseMigrationType(b)
	if err != nil {
		return err
	}
	*m = newm
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for MigrationType.
// It returns the string representation of the enum value as a byte slice
func (m MigrationType) MarshalText() ([]byte, error) {
	return []byte("\"" + m.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MigrationType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (m *MigrationType) UnmarshalText(b []byte) error {
	newm, err := ParseMigrationType(b)
	if err != nil {
		return err
	}
	*m = newm
	return nil
}

// Scan implements the database/sql.Scanner interface for MigrationType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (m *MigrationType) Scan(value any) error {
	newm, err := ParseMigrationType(value)
	if err != nil {
		return err
	}
	*m = newm
	return nil
}

// Value implements the database/sql/driver.Valuer interface for MigrationType.
// It returns the string representation of the enum value.
func (m MigrationType) Value() (driver.Value, error) {
	return m.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for MigrationType.
// It returns the binary representation of the enum value as a byte slice.
func (m MigrationType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + m.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for MigrationType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (m *MigrationType) UnmarshalBinary(b []byte) error {
	newm, err := ParseMigrationType(b)
	if err != nil {
		return err
	}
	*m = newm
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for MigrationType.
// It returns the string representation of the enum value.
func (m MigrationType) MarshalYAML() ([]byte, error) {
	return []byte(m.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (m *MigrationType) UnmarshalYAML(b []byte) error {
	newm, err := ParseMigrationType(b)
	if err != nil {
		return err
	}
	*m = newm
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// migrationtypeNames is a constant string slice containing all enum values cononical absolute names
const migrationtypeNames = "unknowngoose"

// migrationtypeNamesMap is a map of enum values to their canonical absolute
// name positions within the migrationtypeNames string slice
var migrationtypeNamesMap = map[MigrationType]string{
	MigrationTypes.UNKNOWN: migrationtypeNames[0:7],
	MigrationTypes.GOOSE:   migrationtypeNames[7:12],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (m MigrationType) String() string {
	if str, ok := migrationtypeNamesMap[m]; ok {
		return str
	}
	return fmt.Sprintf("migrationtype(%d)", m.migrationType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[unknown]
	_ = x[goose-1]
}
