// DO NOT EDIT.
// code generated by goenums v0.4.3 at May 15 13:54:47.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c ./models/enums/search_condition/search_condition.go

package searchcondition

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// SearchCondition is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type SearchCondition struct {
	searchCondition
}

// searchConditionsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the SearchCondition type.
type searchConditionsContainer struct {
	UNKNOWN  SearchCondition
	CONTAINS SearchCondition
	STARTS   SearchCondition
	ENDS     SearchCondition
	EQUALS   SearchCondition
}

// SearchConditions is a main entry point using the SearchCondition type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var SearchConditions = searchConditionsContainer{
	UNKNOWN: SearchCondition{
		searchCondition: unknown,
	},
	CONTAINS: SearchCondition{
		searchCondition: contains,
	},
	STARTS: SearchCondition{
		searchCondition: starts,
	},
	ENDS: SearchCondition{
		searchCondition: ends,
	},
	EQUALS: SearchCondition{
		searchCondition: equals,
	},
}

// invalidSearchCondition is an invalid sentinel value for SearchCondition
var invalidSearchCondition = SearchCondition{
	searchCondition: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s searchConditionsContainer) allSlice() []SearchCondition {
	return []SearchCondition{
		SearchConditions.CONTAINS,
		SearchConditions.STARTS,
		SearchConditions.ENDS,
		SearchConditions.EQUALS,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s searchConditionsContainer) All() iter.Seq[SearchCondition] {
	return func(yield func(SearchCondition) bool) {
		for _, v := range s.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseSearchCondition = errors.New("invalid input provided to parse to SearchCondition")

// ParseSearchCondition parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseSearchCondition(input any) (SearchCondition, error) {
	switch v := input.(type) {
	case SearchCondition:
		return v, nil
	case string:
		if result := stringToSearchCondition(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToSearchCondition(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToSearchCondition(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToSearchCondition(v); result != nil {
			return *result, nil
		}
	default:
		return invalidSearchCondition, fmt.Errorf("invalid type %T", input)
	}
	return invalidSearchCondition, fmt.Errorf("%w: invalid value %v", ErrParseSearchCondition, input)
}

// searchConditionsNameMap is a map of enum values to their SearchCondition representation
// It is used to convert string representations of enum values into their SearchCondition representation.
var searchConditionsNameMap = map[string]SearchCondition{
	"unknown":  SearchConditions.UNKNOWN,
	"contains": SearchConditions.CONTAINS,
	"starts":   SearchConditions.STARTS,
	"ends":     SearchConditions.ENDS,
	"equals":   SearchConditions.EQUALS,
}

// stringToSearchCondition converts a string representation of an enum value into its SearchCondition representation
// It returns a pointer to the SearchCondition representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToSearchCondition(s string) *SearchCondition {
	if t, ok := searchConditionsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToSearchCondition converts a numeric value to a SearchCondition
// It returns a pointer to the SearchCondition representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToSearchCondition[T number](num T) *SearchCondition {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(SearchConditions.allSlice()) {
		return nil
	}
	result := SearchConditions.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveSearchConditions iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveSearchConditions(f func(SearchCondition)) {
	for _, p := range SearchConditions.allSlice() {
		f(p)
	}
}

// validSearchConditions is a map of enum values to their validity
var validSearchConditions = map[SearchCondition]bool{
	SearchConditions.UNKNOWN:  false,
	SearchConditions.CONTAINS: true,
	SearchConditions.STARTS:   true,
	SearchConditions.ENDS:     true,
	SearchConditions.EQUALS:   true,
}

// IsValid checks whether the SearchConditions value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (s SearchCondition) IsValid() bool {
	return validSearchConditions[s]
}

// MarshalJSON implements the json.Marshaler interface for SearchCondition.
// It returns the JSON representation of the enum value as a byte slice.
func (s SearchCondition) MarshalJSON() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchCondition.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (s *SearchCondition) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	news, err := ParseSearchCondition(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for SearchCondition.
// It returns the string representation of the enum value as a byte slice
func (s SearchCondition) MarshalText() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SearchCondition.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SearchCondition) UnmarshalText(b []byte) error {
	news, err := ParseSearchCondition(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Scan implements the database/sql.Scanner interface for SearchCondition.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (s *SearchCondition) Scan(value any) error {
	news, err := ParseSearchCondition(value)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Value implements the database/sql/driver.Valuer interface for SearchCondition.
// It returns the string representation of the enum value.
func (s SearchCondition) Value() (driver.Value, error) {
	return s.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for SearchCondition.
// It returns the binary representation of the enum value as a byte slice.
func (s SearchCondition) MarshalBinary() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for SearchCondition.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SearchCondition) UnmarshalBinary(b []byte) error {
	news, err := ParseSearchCondition(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for SearchCondition.
// It returns the string representation of the enum value.
func (s SearchCondition) MarshalYAML() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (s *SearchCondition) UnmarshalYAML(b []byte) error {
	news, err := ParseSearchCondition(b)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// searchconditionNames is a constant string slice containing all enum values cononical absolute names
const searchconditionNames = "unknowncontainsstartsendsequals"

// searchconditionNamesMap is a map of enum values to their canonical absolute
// name positions within the searchconditionNames string slice
var searchconditionNamesMap = map[SearchCondition]string{
	SearchConditions.UNKNOWN:  searchconditionNames[0:7],
	SearchConditions.CONTAINS: searchconditionNames[7:15],
	SearchConditions.STARTS:   searchconditionNames[15:21],
	SearchConditions.ENDS:     searchconditionNames[21:25],
	SearchConditions.EQUALS:   searchconditionNames[25:31],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (s SearchCondition) String() string {
	if str, ok := searchconditionNamesMap[s]; ok {
		return str
	}
	return fmt.Sprintf("searchcondition(%d)", s.searchCondition)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[unknown]
	_ = x[contains-1]
	_ = x[starts-2]
	_ = x[ends-3]
	_ = x[equals-4]
}
