// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/http/http_server/contracts/http_server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	contracts "frisboo-bank/openapi-generator-service/pkg/http/http_server/contracts"
	httpservertype "frisboo-bank/openapi-generator-service/pkg/http/http_server/models/enums/http_server_type"
	contracts0 "frisboo-bank/openapi-generator-service/pkg/logger/contracts"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHTTPServer is a mock of HTTPServer interface.
type MockHTTPServer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerMockRecorder
}

// MockHTTPServerMockRecorder is the mock recorder for MockHTTPServer.
type MockHTTPServerMockRecorder struct {
	mock *MockHTTPServer
}

// NewMockHTTPServer creates a new mock instance.
func NewMockHTTPServer(ctrl *gomock.Controller) *MockHTTPServer {
	mock := &MockHTTPServer{ctrl: ctrl}
	mock.recorder = &MockHTTPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServer) EXPECT() *MockHTTPServerMockRecorder {
	return m.recorder
}

// AddMiddlewares mocks base method.
func (m *MockHTTPServer) AddMiddlewares(middlewares ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddMiddlewares", varargs...)
}

// AddMiddlewares indicates an expected call of AddMiddlewares.
func (mr *MockHTTPServerMockRecorder) AddMiddlewares(middlewares ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddlewares", reflect.TypeOf((*MockHTTPServer)(nil).AddMiddlewares), middlewares...)
}

// ListRoutes mocks base method.
func (m *MockHTTPServer) ListRoutes() []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutes")
	ret0, _ := ret[0].([]any)
	return ret0
}

// ListRoutes indicates an expected call of ListRoutes.
func (mr *MockHTTPServerMockRecorder) ListRoutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutes", reflect.TypeOf((*MockHTTPServer)(nil).ListRoutes))
}

// Logger mocks base method.
func (m *MockHTTPServer) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockHTTPServerMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockHTTPServer)(nil).Logger))
}

// Name mocks base method.
func (m *MockHTTPServer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHTTPServerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHTTPServer)(nil).Name))
}

// RouteBuilder mocks base method.
func (m *MockHTTPServer) RouteBuilder() contracts.RouteBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteBuilder")
	ret0, _ := ret[0].(contracts.RouteBuilder)
	return ret0
}

// RouteBuilder indicates an expected call of RouteBuilder.
func (mr *MockHTTPServerMockRecorder) RouteBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteBuilder", reflect.TypeOf((*MockHTTPServer)(nil).RouteBuilder))
}

// SetupDefaultMiddlewares mocks base method.
func (m *MockHTTPServer) SetupDefaultMiddlewares() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupDefaultMiddlewares")
}

// SetupDefaultMiddlewares indicates an expected call of SetupDefaultMiddlewares.
func (mr *MockHTTPServerMockRecorder) SetupDefaultMiddlewares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDefaultMiddlewares", reflect.TypeOf((*MockHTTPServer)(nil).SetupDefaultMiddlewares))
}

// Start mocks base method.
func (m *MockHTTPServer) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHTTPServerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHTTPServer)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockHTTPServer) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHTTPServerMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHTTPServer)(nil).Stop), ctx)
}

// Type mocks base method.
func (m *MockHTTPServer) Type() httpservertype.HttpServerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(httpservertype.HttpServerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockHTTPServerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockHTTPServer)(nil).Type))
}

// MockHTTPServerAdapter is a mock of HTTPServerAdapter interface.
type MockHTTPServerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerAdapterMockRecorder
}

// MockHTTPServerAdapterMockRecorder is the mock recorder for MockHTTPServerAdapter.
type MockHTTPServerAdapterMockRecorder struct {
	mock *MockHTTPServerAdapter
}

// NewMockHTTPServerAdapter creates a new mock instance.
func NewMockHTTPServerAdapter(ctrl *gomock.Controller) *MockHTTPServerAdapter {
	mock := &MockHTTPServerAdapter{ctrl: ctrl}
	mock.recorder = &MockHTTPServerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServerAdapter) EXPECT() *MockHTTPServerAdapterMockRecorder {
	return m.recorder
}

// AddMiddlewares mocks base method.
func (m *MockHTTPServerAdapter) AddMiddlewares(middlewares ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddMiddlewares", varargs...)
}

// AddMiddlewares indicates an expected call of AddMiddlewares.
func (mr *MockHTTPServerAdapterMockRecorder) AddMiddlewares(middlewares ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddlewares", reflect.TypeOf((*MockHTTPServerAdapter)(nil).AddMiddlewares), middlewares...)
}

// ListRoutes mocks base method.
func (m *MockHTTPServerAdapter) ListRoutes() []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutes")
	ret0, _ := ret[0].([]any)
	return ret0
}

// ListRoutes indicates an expected call of ListRoutes.
func (mr *MockHTTPServerAdapterMockRecorder) ListRoutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutes", reflect.TypeOf((*MockHTTPServerAdapter)(nil).ListRoutes))
}

// Logger mocks base method.
func (m *MockHTTPServerAdapter) Logger() contracts0.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(contracts0.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockHTTPServerAdapterMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockHTTPServerAdapter)(nil).Logger))
}

// Name mocks base method.
func (m *MockHTTPServerAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHTTPServerAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHTTPServerAdapter)(nil).Name))
}

// RouteBuilder mocks base method.
func (m *MockHTTPServerAdapter) RouteBuilder() contracts.RouteBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteBuilder")
	ret0, _ := ret[0].(contracts.RouteBuilder)
	return ret0
}

// RouteBuilder indicates an expected call of RouteBuilder.
func (mr *MockHTTPServerAdapterMockRecorder) RouteBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteBuilder", reflect.TypeOf((*MockHTTPServerAdapter)(nil).RouteBuilder))
}

// SetupDefaultMiddlewares mocks base method.
func (m *MockHTTPServerAdapter) SetupDefaultMiddlewares() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupDefaultMiddlewares")
}

// SetupDefaultMiddlewares indicates an expected call of SetupDefaultMiddlewares.
func (mr *MockHTTPServerAdapterMockRecorder) SetupDefaultMiddlewares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDefaultMiddlewares", reflect.TypeOf((*MockHTTPServerAdapter)(nil).SetupDefaultMiddlewares))
}

// Start mocks base method.
func (m *MockHTTPServerAdapter) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHTTPServerAdapterMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHTTPServerAdapter)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockHTTPServerAdapter) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHTTPServerAdapterMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHTTPServerAdapter)(nil).Stop), ctx)
}

// Type mocks base method.
func (m *MockHTTPServerAdapter) Type() httpservertype.HttpServerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(httpservertype.HttpServerType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockHTTPServerAdapterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockHTTPServerAdapter)(nil).Type))
}
